</$objtype/mkfile

LIB=/$objtype/lib/libventi.a

OFILES=\
	packet.$O\
	plan9.$O\
	score.$O\
	sha1-plan9.$O\
	venti.$O\
	errfmt.$O\
	util.$O\

HFILES=\
	packet.h\
	session.h\

CFLAGS=$CFLAGS

</sys/src/cmd/mksyslib

$O.vttest: vttest.$O $OFILES
	$LD $LDFLAGS -o $target $prereq

acid:	$HFILES packet.c
	$CC $INC -a packet.c > acid || rm acid

test: $O.vttest
	$O.vttest
