\&.c	cable	J2
\&	reset-	,RESET-	% 6 64 56
\&	int-	,INT-	% 6 64 72
\&	ds-	,DS-	% 6 64 88
\&	we-	,WE-	% 6 64 104
\&	ack-	,ACK-	% 6 64 120
\&	pd<0:7>	,PD?	% 6 64 136
\&	port-	,PORT-	% 6 64 152
\&	pa<0:5>	,PA?	% 6 64 168
\&.c	plane	P2
\&	pa<0:5>	,PA?	% 4 144 168
\&	reset-	,RESET-	% 4 144 56
\&	int-	,INT-	% 4 144 72
\&	ds-	,DS-	% 4 144 88
\&	we-	,WE-	% 4 144 104
\&	ack-	,ACK-	% 4 144 120
\&	port-	,PORT-	% 4 144 152
\&	pd<0:7>	,PD?	% 4 144 136
