MKSHELL=rc
<$NXM/$objtype/mkfile

OFILES=\
	disk.$O\
	proto.$O\
	scsi.$O\

HFILES=$NXM/sys/include/disk.h
LIB=$NXM/$objtype/lib/libdisk.a

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:$NXM/$objtype/%=/386/%}\

<$NXM/sys/src/cmd/mksyslib

$O.test: test.$O $LIB
	$LD -o $target test.$O $LIB
