APE=/sys/src/ape
<$APE/config
LIB=/$objtype/lib/ape/libap.a
OFILES=\
	div.$O\
	getfcr.$O\
	lock.$O\
	main9.$O\
	main9p.$O\
	memchr.$O\
	memcmp.$O\
	memmove.$O\
	memset.$O\
	notetramp.$O\
	setjmp.$O\
	strcat.$O\
	strchr.$O\
	strcpy.$O\
	strlen.$O\
	tas.$O\
	vlop.$O\
	vlrt.$O\

</sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE

