BUILTINS=
NPROC=1
SYSH=/sys/src/libc/9syscall/sys.h

all:V:
	SYS=`{sed 's/#define.([A-Z0-9_]*).*/\1/' $SYSH}
	for(I in $SYS) {
		n=`{sed -n '/[ 	]'$I'[ 	]/s/.*	//p' $SYSH}
		echo TEXT _$I'(SB)', 1, '$-4' > _$I.s
		echo MOVW '$'$n, R0 >> _$I.s
		echo SWI 0 >> _$I.s
		echo RET >> _$I.s
	}

clean:V:
	rm -f _*.s
