void	clumploop(Clump*, Point, int, void (*)(void*, void*), void*);
void	comborder(Sym*, Sym*);
void	displayer(char*, int);
void	disptexture(void);
void	endclump(Clump*);
void	endpath(Path*);
void	error(char*, ...);
void	execlump(char*, Point, int, void(*)(void*, void*), ...);
void	fillclump(char*);
int	gerbconv(void*, Fconv*);
void	gerberaper(int);
void	gerberin(char*, int);
void	gerberout(void);
void	gerberpath(Path*);
void	gerberrect(Rectangle);
void	gerbertext(Text*);
void	getclump(char*);
Sym*	getlayer(char*);
Hershey* hersheychar(Hfont*, int);
void	hersheydraw(Hershey*, FPoint, int, FPoint);
Hfont*	hersheyfont(char*);
int	hersheywid(Hfont*, int);
void*	new(int);
int	nextint(char**, int);
Point	nextpt(char**);
char*	nextstr(char**);
void	prborder(Biobuf*);
void	prclump(Biobuf*, char*);
void	probject(Biobuf*, void*);
void	rect(Bitmap*, Rectangle, int, Fcode);
char*	savestr(char*);
Sym*	symfind(char*);
void	symprint(Biobuf*);
Sym*	symstore(char*);
void	symtraverse(void(*)(Sym*, void*), ...);
void	xyborder(char*);
void	xyinit(void);
Sym*	xyread(char*);
void	wrclump(Clump*, void*);
void	wrpath(Path*, Point);
