</$objtype/mkfile
#
#		programs
#
DIRS=`{cat commands | awk '{print $2}'}

#</sys/src/cmd/mkmany

all:V:	$DIRS

$DIRS:V:
	for (i in $DIRS) @{
		echo BUILD $i
		ls $i
		cd $i
		GOARCH=$objtype go build
	}

install:V:	installdirs

installdirs:V:
	for (i in $DIRS) @{
		echo INSTALL $i
		ls $i
		cd $i
		GOARCH=$objtype go build
		cp $i /$objtype/bin/	
	}

cleandirs:V:
	for (i in $DIRS) @{
		echo clean $i
		cd $i
		rm $i
	}

update:V:
	for (i in $DIRS) @{
		echo TODO: update $i
		cd $i
		echo update not yet implemented
	}

clean:V:
	mk cleandirs

nuke:V:	cleandirs
