< /$objtype/mkfile

TARG=pic
OFILES=picy.$O\
	picl.$O\
	main.$O\
	print.$O\
	misc.$O\
	symtab.$O\
	blockgen.$O\
	boxgen.$O\
	circgen.$O\
	arcgen.$O\
	linegen.$O\
	movegen.$O\
	textgen.$O\
	input.$O\
	for.$O\
	pltroff.$O\

HFILES=pic.h\
	y.tab.h\

YFILES=picy.y\

BIN=/$objtype/bin
</sys/src/cmd/mkone
CC=pcc
LD=pcc
CFLAGS=-c
YFLAGS=-S -d

picy.c:	y.tab.c
	mv $prereq $target

picl.c:	picl.lx
	$LEX -t $prereq > $target

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.? y.debug $TARG picy.c picl.c
