int	binslot(int);
Biobuf*	Btmpfile(void);
void	coord(Pinent*, char**);
int	cornset(void);
int	findlast(void);
int	findz(void);
void	home(void);
int	install(void);
void	lastw(int);
void	list(void);
int	movptr(int, int);
void	pinsort(void);
void	prdir(void);
void	prpin(Pinent*);
void	prpinxy(Pinent*);
void	prwir(int);
void	putbin(int, int);
void	putdirn(void);
int	rdcmd(void);
int	rdkey(void);
char*	rdstr(void);
void	rotate(Pinent*);
int	scan(int);
int	testdir(Pinent*, Pinent*, int);
int	wrd(void);
int	wwcmd(int, int, int);
void	wwinit(void);
int	wwmove(int, int);
