MKSHELL=rc
<$NXM/$objtype/mkfile

TARG = \
	badsyscall\
	float\
	frexp\
	mixedfloat\
	sysstatread\
	idseg\
	nanotime\

DIRS=

BIN=$NXM/$objtype/bin/regress
HFILES=

UPDATE=\
	mkfile\
	callbadsys.s\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

<$NXM/sys/src/cmd/mkmany

clean:V:
	rm -f [$OS].* *.[$OS]

nuke:V:
	rm -f *.[$OS] y.tab.? y.debug y.output [$OS].$TARG $TARG

$O.badsyscall:	badsyscall.$O callbadsys.$O
	$LD $LDFLAGS -o $target $prereq
