MKSHELL=rc
<$NXM/$objtype/mkfile

TARG=fdisk prep

YFILES=calc.y
HFILES=edit.h
OFILES=\
	edit.$O\
	y.tab.$O\

BIN=$NXM/$objtype/bin/disk

UPDATE=\
	mkfile\
	$NXM/sys/g/man/8/prep\
	edit.c\
	${TARG:%=%.c}\
	$HFILES\
	$YFILES\
	${TARG:%=/386/bin/disk/%}\

<$NXM/sys/src/cmd/mkmany
