CFLAGS=-nostdinc \
	-mcmodel=small \
	-O0 \
	-fplan9-extensions \
	-mno-red-zone \
	-ffreestanding \
	-fno-builtin \
	-trigraphs \
	-Wall \
	-Wno-missing-braces \
	-Wno-parentheses \
	-Wno-unknown-pragmas \
	-Wuninitialized \
	-Wmaybe-uninitialized \
	-I $(APE_PATH)/$(ARCH)/include \
	-I$(APE_PATH)/sys/include

LDFLAGS=-nostdlib \
	-e _main \
	-L $(APE_PATH)/$(ARCH) \
	-lbsd -lap -lc

hi: hi.o
	ld -o hiape hiape.o $(LDFLAGS)
hi.o: hi.c
	cc $(CFLAGS) -c hi.c

