</$objtype/mkfile

TARG=fsim
OFILES=\
	datn.$O\
	data.$O\
	datm.$O\
	plane.$O\
	vor.$O\
	navaid.$O\
	dgy.$O\
	subr.$O\
	adf.$O\
	main.$O\
	mgv.$O\
	isin.$O\
	inp.$O\
	att.$O\
	clk.$O\
	ihyp.$O\
	pwr.$O\
	alt.$O\
	iatan.$O\
	tab.$O\
	roc.$O\
	asi.$O\
	junk.$O\
	aport.$O\
	mkb.$O\

HFILES=\
	type.h\

BIN=/$objtype/bin/games

</sys/src/cmd/mkone
