APE=/sys/src/ape
<$APE/config
LIB=/$objtype/lib/ape/libap.a
OFILES=\
	_seek.$O\
	cycles.$O\
	divl.$O\
	divq.$O\
	getfcr.$O\
	lock.$O\
	main9.$O\
	main9p.$O\
	memcpy.$O\
	memmove.$O\
	memset.$O\
	notetramp.$O\
	setjmp.$O\
	tas.$O\

</sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE

