load("//sys/src/harvey.BUILD", "harvey_binary")

harvey_binary(
    name="factotum",
    install="bin/auth/factotum",
    srcs=[
        "apop.c",
        "chap.c",
        "confirm.c",
        "fs.c",
        "httpdigest.c",
        "log.c",
        "p9any.c",
        "p9cr.c",
        "p9sk1.c",
        "pass.c",
        "rpc.c",
        "rsa.c",
        "secstore.c",
        "util.c",
        "wep.c",
    ],
)
