RCFILES=mail\
	go.fishing\

all:VQ:
	;

installall:VQ:	install
	;

install:V: mail go.fishing gone.msg gone.fishing
	cp mail go.fishing /rc/bin
	cp gone.msg gone.fishing /mail/lib

safeinstall:V: install

safeinstallall:V: install

clean:VQ:
	;
nuke:V:
	;	# rm /rc/bin/^(mail gone.fishing)

UPDATE=\
	go.fishing\
	gone.fishing\
	gone.msg\
	mail\
	mkfile\
	namefiles\
	qmail\
	remotemail\
	rewrite\

update:V:
	update $UPDATEFLAGS $UPDATE
