objtype=riscv64
</riscv64/mkfile

LIB=/$objtype/lib/libmp.a
OFILES=\
#	mpvecadd.$O\
#	mpvecdigmuladd.$O\
#	mpvecdigmulsub.$O\
#	mpvecsub.$O\

HFILES=/$objtype/include/u.h /sys/include/mp.h ../port/dat.h

UPDATE=\
	mkfile\
	$HFILES\

</sys/src/cmd/mksyslib
