<$ROOT/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libflate.a
OFILES=\
	deflate.$O\
	deflatezlib.$O\
	deflateblock.$O\
	deflatezlibblock.$O\
	inflate.$O\
	inflatezlib.$O\
	inflateblock.$O\
	inflatezlibblock.$O\
	flateerr.$O\
	crc.$O\
	adler.$O\

HFILES=\
	$ROOT/sys/include/flate.h\
	zlib.h\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

<$ROOT/sys/src/cmd/mksyslib
