approve_by_comment: true
approve_regex: '^(LGTM|:\+1:|\+1)'
reject_regex: '^(NMW|:-1:|-1)'
reset_on_push: false
signed_off_by:
    required: true
always_pending:
    title_regex: '(WIP|wip)'
    labels:
        - wip
    # custom message that will be used for the GitHub status
    explanation: 'Author of this PR has marked it WIP please do not review this'
reviewers:
  members:
  - 0intro
  - aki5
  - dancrossnyc
  - elbing
  - floren
  - fuchicar
  - hdonnay
  - keedon
  - rminnich
  - sevki
  name: Harvey-OS/core
  required: 1
