objcopy(
	name="harvey",
	deps=[
		"//sys/src/9/amd64:harvey"
	],
	infile="elf64-x86-64",
	outfile="elf32-i386",
)

move(
	name="kernel",
	deps=[
		":harvey",
		"//sys/src/9/amd64:init",
		"//sys/src/cmd/ip/ipconfig:ipconfig",
		"//sys/src/cmd/auth/factotum:factotum",
		"//sys/src/cmd/acme:acme",
	"//sys/src/cmd/acpi:irq",
	"//sys/src/cmd:ascii",
	"//sys/src/cmd:awd",
	"//sys/src/cmd:basename",
	"//sys/src/cmd:bind",
	"//sys/src/cmd:bsplit",
	"//sys/src/cmd:cal",
	"//sys/src/cmd:calendar",
	"//sys/src/cmd:calls",
	"//sys/src/cmd:cat",
	"//sys/src/cmd:chgrp",
	"//sys/src/cmd:chmod",
	"//sys/src/cmd:cleanname",
	"//sys/src/cmd:clock",
	"//sys/src/cmd:cmp",
	"//sys/src/cmd:col",
	"//sys/src/cmd:colors",
	"//sys/src/cmd:comm",
	"//sys/src/cmd:cp",
	"//sys/src/cmd:cpu",
	"//sys/src/cmd:crop",
	"//sys/src/cmd:date",
	"//sys/src/cmd:dc",
	"//sys/src/cmd:dd",
	"//sys/src/cmd:deroff",
	"//sys/src/cmd:du",
	"//sys/src/cmd:echo",
	"//sys/src/cmd:ecp",
	"//sys/src/cmd:ed",
	"//sys/src/cmd:factor",
	"//sys/src/cmd:fcp",
	"//sys/src/cmd:field",
	"//sys/src/cmd:file",
	"//sys/src/cmd:fmt",
	"//sys/src/cmd:fortune",
	"//sys/src/cmd:freq",
	"//sys/src/cmd:getmap",
	"//sys/src/cmd:gview",
	"//sys/src/cmd:hget",
	"//sys/src/cmd:histogram",
	"//sys/src/cmd:history",
	"//sys/src/cmd:html2ms",
	"//sys/src/cmd:iconv",
	"//sys/src/cmd:idiff",
	"//sys/src/cmd:import",
	"//sys/src/cmd:init",
	"//sys/src/cmd:join",
	"//sys/src/cmd:kbmap",
	"//sys/src/cmd:kiss",
	"//sys/src/cmd:ktrace",
	"//sys/src/cmd:lens",
	"//sys/src/cmd:lnfs",
	"//sys/src/cmd:lock",
	"//sys/src/cmd:look",
	"//sys/src/cmd:ls",
	"//sys/src/cmd:mc",
	"//sys/src/cmd:mclock",
	"//sys/src/cmd:md5sum",
	"//sys/src/cmd:mkdir",
	"//sys/src/cmd:mntgen",
	"//sys/src/cmd:mount",
	"//sys/src/cmd:ms2html",
	"//sys/src/cmd:ms",
	"//sys/src/cmd:mtime",
	"//sys/src/cmd:mug",
	"//sys/src/cmd:mv",
	"//sys/src/cmd:netstat",
	"//sys/src/cmd:news",
	"//sys/src/cmd:nm",
	"//sys/src/cmd:nntpfs",
	"//sys/src/cmd:ns",
	"//sys/src/cmd:pbd",
	"//sys/src/cmd:p",
	"//sys/src/cmd:pipefile",
	"//sys/src/cmd:pr",
	"//sys/src/cmd:primes",
	"//sys/src/cmd:ps",
	"//sys/src/cmd:pump",
	"//sys/src/cmd:pwd",
	"//sys/src/cmd:ramfs",
	"//sys/src/cmd:ratrace",
	"//sys/src/cmd:read",
	"//sys/src/cmd:resample",
	"//sys/src/cmd:rm",
	"//sys/src/cmd:rx",
	"//sys/src/cmd:screenlock",
	"//sys/src/cmd:seconds",
	"//sys/src/cmd:sed",
	"//sys/src/cmd:seq",
	"//sys/src/cmd:sha1sum",
	"//sys/src/cmd:size",
	"//sys/src/cmd:sleep",
	"//sys/src/cmd:sort",
	"//sys/src/cmd:split",
	"//sys/src/cmd:srv",
	"//sys/src/cmd:srvfs",
	"//sys/src/cmd:stats",
	"//sys/src/cmd:strace",
	"//sys/src/cmd:strings",
	"//sys/src/cmd:strip",
	"//sys/src/cmd:sum",
	"//sys/src/cmd:swap",
	"//sys/src/cmd:tail",
	"//sys/src/cmd:tar",
	"//sys/src/cmd:tee",
	"//sys/src/cmd:testalarm",
	"//sys/src/cmd:test",
	"//sys/src/cmd:time",
	"//sys/src/cmd:tlsclient",
	"//sys/src/cmd:tlssrv",
	"//sys/src/cmd:touch",
	"//sys/src/cmd:trace",
	"//sys/src/cmd:tr",
	"//sys/src/cmd:tweak",
	"//sys/src/cmd:unicode",
	"//sys/src/cmd:uniq",
	"//sys/src/cmd:unlnfs",
	"//sys/src/cmd:unmount",
	"//sys/src/cmd:wc",
	"//sys/src/cmd:webcookies",
	"//sys/src/cmd:webfsget",
	"//sys/src/cmd:winwatch",
	"//sys/src/cmd:xd",
	"//sys/src/cmd:yacc",
		"//sys/src/libacpi:libacpi",
		"//sys/src/libc:libc",
		"//sys/src/libip:libip",
		"//sys/src/libdraw:libdraw",
		"//sys/src/lib9p:lib9p",
		"//sys/src/libString:libString",
		"//sys/src/libauth:libauth",
		"//sys/src/libauthsrv:libauthsrv",
		"//sys/src/libbin:libbin",
		"//sys/src/libbio:libbio",
		"//sys/src/libcomplete:libcomplete",
		"//sys/src/libcontrol:libcontrol",
		"//sys/src/libdisk:libdisk",
		"//sys/src/libflate:libflate",
		"//sys/src/libframe:libframe",
		"//sys/src/libgeometry:libgeometry",
		"//sys/src/libhttpd:libhttpd",
		"//sys/src/liblex:liblex",
		"//sys/src/libmach:libmach",
		"//sys/src/libmemdraw:libmemdraw",
		"//sys/src/libmemlayer:libmemlayer",
		"//sys/src/libmp:libmp",
		"//sys/src/libndb:libndb",
		"//sys/src/liboventi:liboventi",
		"//sys/src/libplumb:libplumb",
		"//sys/src/libregexp:libregexp",
		"//sys/src/libsec:libsec",
		"//sys/src/libstdio:libstdio",
		"//sys/src/libthread:libthread",
		"//sys/src/libusb:libusb",
		"//sys/src/libventi:libventi",
	],
	installs={
		"amd64/lib/libacpi.a": "lib/libacpi.a",
		"amd64/lib/libc.a": "lib/libc.a",
		"amd64/lib/libip.a": "lib/libip.a",
		"amd64/lib/libdraw.a": "lib/libdraw.a",
		"amd64/lib/lib9p.a": "lib/lib9p.a",
		"amd64/lib/libString.a": "lib/libString.a",
		"amd64/lib/libauth.a": "lib/libauth.a",
		"amd64/lib/libauthsrv.a": "lib/libauthsrv.a",
		"amd64/lib/libbin.a": "lib/libbin.a",
		"amd64/lib/libbio.a": "lib/libbio.a",
		"amd64/lib/libcomplete.a": "lib/libcomplete.a",
		"amd64/lib/libcontrol.a": "lib/libcontrol.a",
		"amd64/lib/libdisk.a": "lib/libdisk.a",
		"amd64/lib/libflate.a": "lib/libflate.a",
		"amd64/lib/libframe.a": "lib/libframe.a",
		"amd64/lib/libgeometry.a": "lib/libgeometry.a",
		"amd64/lib/libhttpd.a": "lib/libhttpd.a",
		"amd64/lib/liblex.a": "lib/liblex.a",
		"amd64/lib/libmach.a": "lib/libmach.a",
		"amd64/lib/libmemdraw.a": "lib/libmemdraw.a",
		"amd64/lib/libmemlayer.a": "lib/libmemlayer.a",
		"amd64/lib/libmp.a": "lib/libmp.a",
		"amd64/lib/libndb.a": "lib/libndb.a",
		"amd64/lib/liboventi.a": "lib/liboventi.a",
		"amd64/lib/libplumb.a": "lib/libplumb.a",
		"amd64/lib/libregexp.a": "lib/libregexp.a",
		"amd64/lib/libsec.a": "lib/libsec.a",
		"amd64/lib/libstdio.a": "lib/libstdio.a",
		"amd64/lib/libthread.a": "lib/libthread.a",
		"amd64/lib/libusb.a": "lib/libusb.a",
		"amd64/lib/libventi.a": "lib/libventi.a",
		"sys/src/9/amd64/harvey.32bit": "bin/harvey",
		"amd64/bin/init": "bin/init",
		"amd64/bin/echo": "bin/echo",
		"amd64/bin/ls": "bin/ls",
		"amd64/bin/cat": "bin/cat",
		"amd64/bin/date": "bin/date",
		"amd64/bin/ipconfig": "bin/ipconfig",
		"amd64/bin/acme": "bin/acme",
		"amd64/bin/auth/factotum": "bin/factotum",
		"amd64/bin/mount": "bin/mount",
		"amd64/bin/srv": "bin/srv",
		"amd64/bin/ed": "bin/ed",
		"amd64/bin/ratrace": "bin/ratrace",
		"amd64/bin/ps": "bin/ps",
		"amd64/bin/ascii": "bin/ascii",
		"amd64/bin/awd": "bin/awd",
		"amd64/bin/basename": "bin/basename",
		"amd64/bin/bind": "bin/bind",
		"amd64/bin/bsplit": "bin/bsplit",
		"amd64/bin/cal": "bin/cal",
		"amd64/bin/calendar": "bin/calendar",
		"amd64/bin/calls": "bin/calls",
		"amd64/bin/cat": "bin/cat",
		"amd64/bin/chgrp": "bin/chgrp",
		"amd64/bin/chmod": "bin/chmod",
		"amd64/bin/cleanname": "bin/cleanname",
		"amd64/bin/clock": "bin/clock",
		"amd64/bin/cmp": "bin/cmp",
		"amd64/bin/col": "bin/col",
		"amd64/bin/colors": "bin/colors",
		"amd64/bin/comm": "bin/comm",
		"amd64/bin/cp": "bin/cp",
		"amd64/bin/cpu": "bin/cpu",
		"amd64/bin/crop": "bin/crop",
		"amd64/bin/date": "bin/date",
		"amd64/bin/dc": "bin/dc",
		"amd64/bin/dd": "bin/dd",
		"amd64/bin/deroff": "bin/deroff",
		"amd64/bin/du": "bin/du",
		"amd64/bin/echo": "bin/echo",
		"amd64/bin/ecp": "bin/ecp",
		"amd64/bin/ed": "bin/ed",
		"amd64/bin/factor": "bin/factor",
		"amd64/bin/fcp": "bin/fcp",
		"amd64/bin/field": "bin/field",
		"amd64/bin/file": "bin/file",
		"amd64/bin/fmt": "bin/fmt",
		"amd64/bin/fortune": "bin/fortune",
		"amd64/bin/freq": "bin/freq",
		"amd64/bin/getmap": "bin/getmap",
		"amd64/bin/gview": "bin/gview",
		"amd64/bin/hget": "bin/hget",
		"amd64/bin/histogram": "bin/histogram",
		"amd64/bin/history": "bin/history",
		"amd64/bin/html2ms": "bin/html2ms",
		"amd64/bin/iconv": "bin/iconv",
		"amd64/bin/idiff": "bin/idiff",
		"amd64/bin/import": "bin/import",
		"amd64/bin/init": "bin/init",
		"amd64/bin/join": "bin/join",
		"amd64/bin/kbmap": "bin/kbmap",
		"amd64/bin/kiss": "bin/kiss",
		"amd64/bin/ktrace": "bin/ktrace",
		"amd64/bin/lens": "bin/lens",
		"amd64/bin/lnfs": "bin/lnfs",
		"amd64/bin/lock": "bin/lock",
		"amd64/bin/look": "bin/look",
		"amd64/bin/ls": "bin/ls",
		"amd64/bin/mc": "bin/mc",
		"amd64/bin/mclock": "bin/mclock",
		"amd64/bin/md5sum": "bin/md5sum",
		"amd64/bin/mkdir": "bin/mkdir",
		"amd64/bin/mntgen": "bin/mntgen",
		"amd64/bin/mount": "bin/mount",
		"amd64/bin/ms2html": "bin/ms2html",
		"amd64/bin/ms": "bin/ms",
		"amd64/bin/mtime": "bin/mtime",
		"amd64/bin/mug": "bin/mug",
		"amd64/bin/mv": "bin/mv",
		"amd64/bin/netstat": "bin/netstat",
		"amd64/bin/news": "bin/news",
		"amd64/bin/nm": "bin/nm",
		"amd64/bin/nntpfs": "bin/nntpfs",
		"amd64/bin/ns": "bin/ns",
		"amd64/bin/pbd": "bin/pbd",
		"amd64/bin/p": "bin/p",
		"amd64/bin/pipefile": "bin/pipefile",
		"amd64/bin/pr": "bin/pr",
		"amd64/bin/primes": "bin/primes",
		"amd64/bin/ps": "bin/ps",
		"amd64/bin/pump": "bin/pump",
		"amd64/bin/pwd": "bin/pwd",
		"amd64/bin/ramfs": "bin/ramfs",
		"amd64/bin/ratrace": "bin/ratrace",
		"amd64/bin/read": "bin/read",
		"amd64/bin/resample": "bin/resample",
		"amd64/bin/rm": "bin/rm",
		"amd64/bin/rx": "bin/rx",
		"amd64/bin/screenlock": "bin/screenlock",
		"amd64/bin/seconds": "bin/seconds",
		"amd64/bin/sed": "bin/sed",
		"amd64/bin/seq": "bin/seq",
		"amd64/bin/sha1sum": "bin/sha1sum",
		"amd64/bin/size": "bin/size",
		"amd64/bin/sleep": "bin/sleep",
		"amd64/bin/sort": "bin/sort",
		"amd64/bin/split": "bin/split",
		"amd64/bin/srv": "bin/srv",
		"amd64/bin/srvfs": "bin/srvfs",
		"amd64/bin/stats": "bin/stats",
		"amd64/bin/strace": "bin/strace",
		"amd64/bin/strings": "bin/strings",
		"amd64/bin/strip": "bin/strip",
		"amd64/bin/sum": "bin/sum",
		"amd64/bin/swap": "bin/swap",
		"amd64/bin/tail": "bin/tail",
		"amd64/bin/tar": "bin/tar",
		"amd64/bin/tee": "bin/tee",
		"amd64/bin/testalarm": "bin/testalarm",
		"amd64/bin/test": "bin/test",
		"amd64/bin/time": "bin/time",
		"amd64/bin/tlsclient": "bin/tlsclient",
		"amd64/bin/tlssrv": "bin/tlssrv",
		"amd64/bin/touch": "bin/touch",
		"amd64/bin/trace": "bin/trace",
		"amd64/bin/tr": "bin/tr",
		"amd64/bin/tweak": "bin/tweak",
		"amd64/bin/unicode": "bin/unicode",
		"amd64/bin/uniq": "bin/uniq",
		"amd64/bin/unlnfs": "bin/unlnfs",
		"amd64/bin/unmount": "bin/unmount",
		"amd64/bin/wc": "bin/wc",
		"amd64/bin/webcookies": "bin/webcookies",
		"amd64/bin/webfsget": "bin/webfsget",
		"amd64/bin/winwatch": "bin/winwatch",
		"amd64/bin/xd": "bin/xd",
		"amd64/bin/yacc": "bin/yacc",
	},
)
old_build(
	name="all",
	package="all",
)
