objcopy(
	name="harvey",
	deps=[
		"//sys/src/9/amd64:harvey"
	],
	infile="elf64-x86-64",
	outfile="elf32-i386",
)

kernel(
	name="kernel",
	deps=[
		":harvey",
		"//sys/src/9/amd64:init",
		"//sys/src/cmd:echo",
		"//sys/src/cmd:ls",
		"//sys/src/cmd:cat",
		"//sys/src/cmd:date",
		"//sys/src/cmd/ip/ipconfig:ipconfig",
		"//sys/src/cmd/auth/factotum:factotum",
		"//sys/src/cmd/acme:acme",
		"//sys/src/cmd:mount",
		"//sys/src/cmd:srv",
		"//sys/src/cmd:ed",
		"//sys/src/cmd:ratrace",
		"//sys/src/cmd:ps",
		"//sys/src/libc:libc",
		"//sys/src/libip:libip",
		"//sys/src/libdraw:libdraw",
		"//sys/src/lib9p:lib9p",
		"//sys/src/libString:libString",
		"//sys/src/libauth:libauth",
		"//sys/src/libauthsrv:libauthsrv",
		"//sys/src/libbin:libbin",
		"//sys/src/libbio:libbio",
		"//sys/src/libcomplete:libcomplete",
		"//sys/src/libcontrol:libcontrol",
		"//sys/src/libdisk:libdisk",
		"//sys/src/libflate:libflate",
		"//sys/src/libframe:libframe",
		"//sys/src/libgeometry:libgeometry",
		"//sys/src/libhttpd:libhttpd",
		"//sys/src/liblex:liblex",
		"//sys/src/libmach:libmach",
		"//sys/src/libmemdraw:libmemdraw",
		"//sys/src/libmemlayer:libmemlayer",
		"//sys/src/libmp:libmp",
		"//sys/src/libndb:libndb",
		"//sys/src/liboventi:liboventi",
		"//sys/src/libplumb:libplumb",
		"//sys/src/libregexp:libregexp",
		"//sys/src/libsec:libsec",
		"//sys/src/libstdio:libstdio",
		"//sys/src/libthread:libthread",
		"//sys/src/libusb:libusb",
		"//sys/src/libventi:libventi",
	],
	installs={
		"amd64/lib/libc.a": "lib/libc.a",
		"amd64/lib/libip.a": "lib/libip.a",
		"amd64/lib/libdraw.a": "lib/libdraw.a",
		"amd64/lib/lib9p.a": "lib/lib9p.a",
		"amd64/lib/libString.a": "lib/libString.a",
		"amd64/lib/libauth.a": "lib/libauth.a",
		"amd64/lib/libauthsrv.a": "lib/libauthsrv.a",
		"amd64/lib/libbin.a": "lib/libbin.a",
		"amd64/lib/libbio.a": "lib/libbio.a",
		"amd64/lib/libcomplete.a": "lib/libcomplete.a",
		"amd64/lib/libcontrol.a": "lib/libcontrol.a",
		"amd64/lib/libdisk.a": "lib/libdisk.a",
		"amd64/lib/libflate.a": "lib/libflate.a",
		"amd64/lib/libframe.a": "lib/libframe.a",
		"amd64/lib/libgeometry.a": "lib/libgeometry.a",
		"amd64/lib/libhttpd.a": "lib/libhttpd.a",
		"amd64/lib/liblex.a": "lib/liblex.a",
		"amd64/lib/libmach.a": "lib/libmach.a",
		"amd64/lib/libmemdraw.a": "lib/libmemdraw.a",
		"amd64/lib/libmemlayer.a": "lib/libmemlayer.a",
		"amd64/lib/libmp.a": "lib/libmp.a",
		"amd64/lib/libndb.a": "lib/libndb.a",
		"amd64/lib/liboventi.a": "lib/liboventi.a",
		"amd64/lib/libplumb.a": "lib/libplumb.a",
		"amd64/lib/libregexp.a": "lib/libregexp.a",
		"amd64/lib/libsec.a": "lib/libsec.a",
		"amd64/lib/libstdio.a": "lib/libstdio.a",
		"amd64/lib/libthread.a": "lib/libthread.a",
		"amd64/lib/libusb.a": "lib/libusb.a",
		"amd64/lib/libventi.a": "lib/libventi.a",
		"amd64/harvey": "bin/harvey",
		"amd64/bin/init": "bin/init",
		"amd64/bin/echo": "bin/echo",
		"amd64/bin/ls": "bin/ls",
		"amd64/bin/cat": "bin/cat",
		"amd64/bin/date": "bin/date",
		"amd64/bin/ipconfig": "bin/ipconfig",
		"amd64/bin/acme": "bin/acme",
		"amd64/bin/factotum": "bin/factotum",
		"amd64/bin/mount": "bin/mount",
		"amd64/bin/srv": "bin/srv",
		"amd64/bin/ed": "bin/ed",
		"amd64/bin/ratrace": "bin/ratrace",
		"amd64/bin/ps": "bin/ps",
	},
)
