#!/bin/bash
# This script assumes you have set JENKINSHOME
# in the environment. If you have not it will fail, which
# will be quickly caught by jenkins, so there's no checking.
. $JENKINSHOME/.bashrc
echo "WARNING:This will fail if $NXM/xbin is in your PATH"
set -e
go version
9c --version
cp /$JENKINSHOME/mkconfig.jenkins inferno-os/mkconfig
sh BUILDTOOLCHAIN
# `special` system like suse want . files fully qualified
. ./SETUP
cd sys/src
mk nuke
mk libs
mk install
mk kernels

# Boot the kernel and see if the output we get makes sense
# qemu must be in your path of course. It can be
# the standard command or a shell script to make things
# run correctly. On coreboot.org on my account it is
# a shell script.
qemu-system-x86_64 --kernel nxm/k10/9k8regression.elf  \
	-no-reboot  --nographic </dev/null > qemuout &
qemuproc=$!
sleep 60
# just in case ...
set +e
kill -9 $!
set -e
# things are not always identical. We need to do some filtering.
# For now, just filter on the regression tests themselves.
sed '1,/Morning/d' qemuout | sed 's/badsyscall.*://' | /usr/bin/diff -bw - correctoutput
date

