// Code generated by "stringer -type MountFlag"; DO NOT EDIT.

package harvey

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[REPL-0]
	_ = x[BEFORE-1]
	_ = x[AFTER-2]
	_ = x[CREATE-4]
	_ = x[CACHE-16]
}

const (
	_MountFlag_name_0 = "REPLBEFOREAFTER"
	_MountFlag_name_1 = "CREATE"
	_MountFlag_name_2 = "CACHE"
)

var (
	_MountFlag_index_0 = [...]uint8{0, 4, 10, 15}
)

func (i MountFlag) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _MountFlag_name_0[_MountFlag_index_0[i]:_MountFlag_index_0[i+1]]
	case i == 4:
		return _MountFlag_name_1
	case i == 16:
		return _MountFlag_name_2
	default:
		return "MountFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
