.ds dQ /usr/lib/postscript
.TH POSTBGI 1 "DWB 3.2"
.SH NAME
.B postbgi
\- PostScript translator for
.SM BGI
(Basic Graphical Instructions) files
.SH SYNOPSIS
\*(mBpostbgi\f1
.OP "" options []
.OP "" files []
.SH DESCRIPTION
.B postbgi
translates
.SM BGI
(Basic Graphical Instructions)
.I files
into PostScript and writes the results on the
standard output.
If no
.I files
are specified, or if
.OP \-
is one of the input
.IR files ,
the standard input is read.
The following
.I options
are understood:
.TP 0.75i
.OP \-c num
Print
.I num
copies of each page.
By default only one copy is printed.
.TP
.OP \-f name
Print text using font
.IR name .
Any PostScript font can be used,
although the best results will only be
obtained with constant width fonts.
The default font is Courier.
.TP
.OP \-m num
Magnify each logical page by the factor
.IR num .
Pages are scaled uniformly about the origin,
which by default is located at the center of
each page.
The default magnification is 1.0.
.TP
.OP \-n num
Print
.I num
logical pages on each piece of paper,
where
.I num
can be any positive integer.
By default
.I num
is set to 1.
.TP
.OP \-o list
Print pages whose numbers are given in the comma-separated
.IR list .
The list contains single numbers
.I N
and ranges
.IR N1\-\|N2 .
A missing
.I N1
means the lowest numbered page, a missing
.I N2
means the highest.
.TP
.OP \-p mode
Print
.I files
in either \*(mBportrait\fP or \*(mBlandscape\fP
.IR mode .
Only the first character of
.I mode
is significant.
The default
.I mode
is \*(mBportrait\fP.
.TP
.OP \-w num
Set the line width used for graphics to
.I num
points, where a point is approximately 1/72
of an inch.
By default
.I num
is set to 0 points, which forces lines to be
one pixel wide.
.TP
.OP \-x num
Translate the origin
.I num
inches along the positive x axis.
The default
coordinate system has the origin fixed at the
center of the page, with positive
x to the right and positive y up the page.
Positive
.I num
moves everything right.
The default offset is 0 inches.
.TP
.OP \-y num
Translate the origin
.I num
inches along the positive y axis.
Positive
.I num
moves everything up the page.
The default offset is 0 inches.
.TP
.OP \-E name
Set the character encoding for text fonts to
.IR name .
Requesting
.I name
means include file
.MI \*(dQ name .enc \f1.
A nonexistent encoding file is silently ignored.
The default selects file
.MR \*(dQ/Default.enc .
.TP
.OP \-L file
Use
.I file
as the PostScript prologue.
.br
The default is
.MR \*(dQ/postbgi.ps .
.PP
Three options allow insertion of arbitrary PostScript
at controlled points in the translation process:
.TP 0.75i
.OP \-C file
Copy
.I file
to the output file;
.I file
must contain legitimate PostScript.
.TP
.OP \-P string
Include
.I string
in the output file;
.I string
must be legitimate PostScript.
.TP
.OP \-R action
Requests special
.I action
(e.g.,
.MR manualfeed )
on a per page or global basis.
The
.I action
string can be given as
.IR request ,
.IM request : page\f1\|,
or
.IM request : page : file\f1\|.
If
.I page
is omitted or given as 0, the request
applies to all pages.
If
.I file
is omitted, the request
lookup is done in
.MR \*(dQ/ps.requests .
.PP
.B postbgi
can handle
.SM STARE
(black and white) and
.SM PRISM
(color)
.SM BGI
jobs.
By default plots are rigidly scaled to fill the page, which produces
the good results for most
.SM STARE
jobs.
.SM PRISM
jobs typically fill regions with colors, and often require device
specific tuning to produce acceptable results.
Adding the
.MW \-P"/prism\ true\ def"
option is strongly recommended when
.B postbgi
is translating
.SM PRISM
jobs.
.br
.ne 7v
.SH EXAMPLES
For most
.SM STARE
jobs,
.EX
postbgi  \f2file
.EE
gives good results, while
.EX
postbgi \-P"/prism true def"  \f2file
.EE
is recommended when translating
.SM PRISM
jobs.
.SH DIAGNOSTICS
A 0 exit status is returned if
.I files
were successfully processed.
.SH BUGS
The default line width is too small for write-white
print engines, like the one used by the PS-2400.
Several
.SM BGI
opcodes have not been implemented.
.SH FILES
.MW \*(dQ/postbgi.ps
.br
.MW \*(dQ/forms.ps
.br
.MW \*(dQ/ps.requests
.SH SEE ALSO
.BR dpost (1),
.BR postdaisy (1),
.BR postdmd (1),
.BR postio (1),
.BR postmd (1),
.BR postprint (1),
.BR postreverse (1),
.BR posttek (1),
.BR psencoding (1)
