</$objtype/mkfile

SYSTEM=plan9
VERSION=3.3.1

POSTLIB=/sys/lib/postscript/prologues
POSTBIN=/sys/lib/postscript/bin

all:V:	grabit

install installall:V:	$POSTBIN/grabit $POSTLIB/grabit.ps

$POSTBIN/grabit:	grabit
	cp $prereq $target

$POSTLIB/grabit.ps:	grabit.ps
	cp $prereq $target

grabit:	grabit.rc
	sed 's?^POSTLIB=.*?POSTLIB='$POSTLIB'?' grabit.rc >grabit
	chmod 775 grabit

clean nuke:V:
	rm -f grabit
