</$objtype/mkfile

TARG=8l
OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../8c/8.out.h\

BIN=/$objtype/bin
CFILES=${OFILES:%.$O=%.c}
CFILES=${CFILES:enam.c=../8c/enam.c}
UPDATE=\
	mkfile\
	$HFILES\
	$CFILES\
	${TARG:%=/386/bin/%}\

</sys/src/cmd/mkone

enam.$O:	../8c/enam.c
	$CC $CFLAGS ../8c/enam.c

