<$NXM/$objtype/mkfile

LIB=$NXM/$objtype/lib/libfis.a
OFILES=\
	fis.$O\

HFILES=$NXM/sys/include/fis.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

<$NXM/sys/src/cmd/mksyslib
