</$objtype/mkfile

LIB=/$objtype/lib/lib9p.a
OFILES=\
	auth.$O\
	dirread.$O\
	fid.$O\
	file.$O\
	intmap.$O\
	listen.$O\
	mem.$O\
	req.$O\
	parse.$O\
	post.$O\
	rfork.$O\
	srv.$O\
	thread.$O\
	uid.$O\
	util.$O\

HFILES=/sys/include/9p.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

</sys/src/cmd/mksyslib

$O.ramfs: ramfs.$O $LIB
	$LD -o $target $prereq
