MKSHELL=$PLAN9/bin/rc
NPROC=1
<$ROOT/$objtype/mkfile

# Note that mksys needs to be in your path, somewhere.
install:V:
	mksys $objtype
	$(AS) -c *.s
	ar rvu $ROOT/$objtype/lib/libc.a *.$O
	rm -f *.o *.[$OS] *.s

nuke clean:V:
	rm -f *.[$OS] *.s

installall:V:
	for(objtype in $CPUS) mk install

update:V:
	update $UPDATEFLAGS mkfile sys.h

