</$objtype/mkfile

OFILES=\
	main.$O\
	assign.$O\
	preinc.$O\
	postinc.$O\
	predec.$O\
	postdec.$O\
	add.$O\
	sub.$O\
	mul.$O\
	div.$O\
	mod.$O\
	and.$O\
	or.$O\
	xor.$O\
	lsh.$O\
	rsh.$O\

HFILES=\
	type.h\

$O.out:	$OFILES
	$LD $OFILES

%.$O:	%.c
	$CC -N $stem.c

%.$O:	$HFILES

clean:V:
	rm -f *.[$OS] [$OS].out
