</$objtype/mkfile

LIB=/$objtype/lib/libmemdraw.a
FILES=\
	alloc\
	arc\
	cload\
	cmap\
	cread\
	defont\
	draw\
	ellipse\
	fillpoly\
	hwdraw\
	iprint\
	line\
	load\
	openmemsubfont\
	poly\
	read\
	string\
	subfont\
	unload\
	write\

HFILES=\
	/sys/include/memdraw.h\
	/sys/include/draw.h

CFILES=\
	${FILES:%=%.c}\
	mkcmap.c\


OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libmemdraw.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib

$O.drawtime: drawtime.$O $LIB
	$LD -o $target $prereq

$O.drawtest: drawtest.$O $LIB
	$LD -o $target $prereq
 
$O.arctest: arctest.$O ndraw.$O arc.$O $LIB
	$LD -o $target $prereq

$O.test: test.$O $LIB
	$LD -o $target $prereq
