char *odesctab[][2]={
	"1ST",	"first",
	"2ND",	"second",
	"3RD",	"third",
	"4TH",	"fourth",
	"5TH",	"fifth",
	"AB",	"about",
	"ALM",	"almost",
	"AM",	"among",
	"APP",	"appended",
	"ATT",	"attached",
	"B",	"bright(er)",
	"B,",	"bright;",
	"BET",	"between",
	"BF",	"brighter toward following side",
	"BIN",	"binuclear",
	"BM",	"brighter towards middle",
	"BMBN",	"brighter towards bright nucleus",
	"BMN",	"brighter towards nucleus",
	"BN",	"bright toward north side",
	"BP",	"brighter toward preceding side",
	"BS",	"brighter toward south side",
	"BSTNR",	"bright stars near",
	"C",	"compressed|considerably",
	"CB",	"considerably bright",
	"CE",	"considerably extended",
	"CF",	"considerably faint",
	"CH",	"chevelure",
	"CL",	"cluster(member)",
	"CLOSE",	"close",
	"CLOSE F",	"close following",
	"CLOSE P",	"close preceding",
	"CLUSTER",	"cluster",
	"CM",	"compressed in middle",
	"CO",	"coarse(ly)",
	"COM",	"cometic",
	"CON",	"connected with",
	"CONT",	"in contact",
	"CRI",	"considerably rich",
	"CS",	"considerably small",
	"D",	"double|diameter",
	"D*",	"double star",
	"DEF",	"defined",
	"DIAM",	"diam",
	"DIF",	"diffuse",
	"DIFFUSED",	"diffused",
	"DIFFIC",	"difficult",
	"DISC",	"disc",
	"DIST",	"distance",
	"DNEB",	"double nebula",
	"E",	"extended",
	"EB",	"extremely bright",
	"EC",	"extremely compressed",
	"EE",	"most extremely",
	"EEF",	"most extremely faint",
	"EF",	"extremely faint",
	"EL",	"extremely large",
	"ELLIPTIC",	"elliptic",
	"ER",	"easily resolvable",
	"ERI",	"extremely rich",
	"ES",	"extremely small",
	"EXC",	"excentric",
	"F",	"faint|following",
	"F ",	"following",
	"F*",	"faint star",
	"F,",	"faint;",
	"G",	"gradually",
	"GCL",	"globular cluster",
	"GR",	"group",
	"GROUP",	"group",
	"I",	"irregular",
	"IF",	"irregular figure",
	"IN",	"in",
	"IN CENTRE",	"in center",
	"INV",	"involved",
	"IR",	"irregular",
	"L",	"large,long|little",
	"L,",	"large;",
	"LAST",	"last",
	"LBM",	"little brighter in middle",
	"LBP",	"little brighter towards preceding side",
	"LC",	"little compressed",
	"LCL",	"large cluster",
	"LE",	"little extended",
	"LINE",	"in line",
	"M",	"middle",	
	"MBM",	"much brighter in middle",
	"MC",	"much compressed",
	"ME",	"much extended",
	"MM",	"mixed magnitudes",
	"MN",	"milky nebulosity",
	"N",	"nucleus|north",
	"N ",	"north",
	"NEB",	"nebula",
	"NEBULOSITY",	"nebulosity",
	"NEBULOUS",	"nebulous",
	"NF",	"north following",
	"NO",	"no",
	"NP",	"north preceding",
	"NR",	"near",
	"NUCL",	"nucleus",
	"OF",	"of",
	"OR",	"or",
	"P",	"poor|preceding",
	"P ",	"preceding",
	"P,",	"poor,",
	"PB",	"pretty bright",
	"PBN",	"pretty bright nucleus",
	"PC",	"pretty compressed",
	"PF",	"pretty faint",
	"PG",	"pretty good",
	"PGBM",	"pretty gradually brighter towards middle",
	"PL",	"pretty large",
	"PLN",	"planetary nebula",
	"PM",	"pretty much",
	"PR",	"pretty resolvable",
	"PRI",	"pretty rich",
	"PS",	"pretty suddenly|small",
	"PS,",	"pretty small;",
	"PSBM",	"pretty suddenly brighter in middle",
	"PSLBM",	"pretty suddenly little brighter in middle",
	"PSMBM",	"pretty suddenly much brighter in middle",
	"PSVM",	"pretty suddenly very much",
	"QUAD",	"quadrilateral",
	"QUAR",	"quartile",
	"R",	"resolvable",
	"R,",	"round;",
	"RESOLVABLE",	"resolvable",
	"RI",	"rich",
	"RING",	"ring",
	"RN",	"resolvable nucleus",
	"RR",	"exactly round|partially resolved, some stars seen",
	"RRR",	"well resolved,clearly consisting of stars",
	"S ",	"south",
	"S",	"small|suddenly|south",
	"S*",	"small star",
	"S,",	"small;",
	"SBM",	"suddenly brighter in middle",
	"SC",	"scattered",
	"SEV",	"several",
	"SF",	"south following",
	"SH",	"shaped",
	"SM",	"smaller",
	"SMBM",	"suddenly much brighter in middle",
	"SMBMN",	"suddenly much brighter in nucleus",
	"SOUTH",	"south",
	"SP",	"south preceding",
	"SPIR",	"spiral",
	"ST",	"stars",
	"STEL",	"stellar",
	"STELL",	"stellar",
	"STELLAR",	"stellar",
	"STRONGLY",	"strongly",
	"SUSP",	"suspected",
	"TO",	"to",
	"TRAP",	"trapezium",
	"TRAPEZ",	"trapezium",
	"TRI",	"triangle|forms a triangle with",
	"TRIN",	"trinuclear",
	"V",	"very",
	"VAR",	"variable",
	"VB",	"very bright",
	"VBN",	"very bright nucleus",
	"VC",	"very compressed",
	"VF",	"very faint",
	"VG",	"very gradually",
	"VL,",	"very large;",
	"VM",	"very much",
	"VME",	"very much extended",
	"VS",	"very small",
	"VSM",	"very suddenly much",
	"VSBM",	"very suddenly brighter towards middle",
	"VSVM",	"very suddenly very much",
	"VSN",	"very small nucleus",
	"VV",	"very very",
	"W/",	"with",
	0,	0
};
char *ndesctab[][2]={
	")",	"?",
	"-",	"to, of",
	"24-",	"24-inch Schmidt desc.:",
	"ALM",	"almost",
	"AMS",	"arms",
	"AP",	"appendage",
	"APP",	"appendage",
	"APPEARANCE",	"appearance",
	"ARC",	"arc",
	"AREA",	"area",
	"ARMS",	"arms",
	"AROUND",	"around",
	"AT",	"attached",
	"ATT",	"attached",
	"ATT F",	"attached following",
	"ATT N",	"attached north",
	"ATT P",	"attached preceding",
	"ATT S",	"attached south",
	"B",	"bright(er)",
	"BAR",	"bar",
	"BD",	"broad",
	"BDIF",	"bright diffuse",
	"BET",	"between",
	"BIN",	"binuclear",
	"BISECTS",	"bisects",
	"BM",	"brighter toward center",
	"BRIDG",	"bridge",
	"BRIDGE",	"bridge",
	"BRIGHTEST",	"brightest",
	"BRT",	"bright(er)",
	"BRUSHES",	"brushes",
	"BULG",	"bulge",
	"BULGE",	"bulge",
	"CHAIN",	"chain",
	"CL",	"in or near a cluster of galaxies",
	"CLOS",	"close",
	"CLOSE",	"close",
	"CLUSTER",	"in or near a cluster of galaxies",
	"COM",	"companion(s)",
	"COMMON",	"common",
	"COMP",	"compact",
	"COMPL",	"complete",
	"COMPLEX",	"complex",
	"CONNECTS",	"connects",
	"CONT",	"contact",
	"CONT ",	"in contact",
	"CONTACT",	"contact, in contact",
	"CT",	"center",
	"CURVED",	"curved",
	"D",	"defined",
	"DB",	"double",
	"DC",	"(Carlsen 1940)",
	"DEVAUC",	"(de Vaucouleurs)",
	"DIF",	"diffuse(ness)",
	"DIFHALO",	"diffuse halo",
	"DISK",	"disk",
	"DIST",	"distribution",
	"DK",	"dark",
	"DSK",	"disk",
	"DST",	"distorted",
	"DUMBELL",	"dumbbell",
	"DWF",	"dwarf",
	"E",	"elliptical",
	"EDGE",	"edge",
	"EFFECT",	"effect",
	"EL",	"elongated",
	"END",	"end",
	"ENDS",	"ends",
	"EON",	"edge on system",
	"EO",	"equatorial",
	"EQ",	"equally",
	"EXT",	"extended, extensive, extension",
	"EXTEN",	"extended, extensive, extension",
	"F",	"faint|following",
	"F ",	"following",
	"FDIF",	"faint diffuse(ness)",
	"FEATURELESS",	"featureless",
	"FEW",	"few",
	"FIELD",	"field",
	"FIL",	"filament",
	"FL",	"flat",
	"FLD",	"field",
	"FLDSK",	"flat disk",
	"FLAT",	"flat",
	"FO",	"following",
	"FORM",	"form",
	"FORMING",	"forming",
	"FRM",	"form",
	"GALAXY",	"galaxy",
	"GALAXIES",	"galaxies",
	"GRP",	"group",
	"H",	"high",
	"HALO",	"halo",
	"HISB",	"high surface brightness",
	"HSB",	"high surface brightness",
	"I",	"irregular",
	"IMAG",	"image",
	"IMAGE",	"image",
	"IN",	"in",
	"IN CL",	"in cluster of galaxies",
	"INC",	"inclined",
	"INCL",	"inclined",
	"INT",	"internal",
	"INTEN",	"intensity",
	"INTERACT",	"interact",
	"INVIS",	"invisible",
	"INVISIBLE",	"invisible",
	"INVOLVED",	"involved",
	"IRR",	"irregular",
	"IRREG",	"irregular",
	"IRRR",	"irregularly round",
	"JET",	"jet",
	"KN",	"knot",
	"KNS",	"knots",
	"KNOT",	"knot",
	"KNOTS",	"knots",
	"KNOTTY",	"knotty",
	"KNY",	"knotty",
	"LBM",	"little brighter toward center",
	"LG",	"large",
	"LGE",	"large",
	"LIKE",	"like",
	"LINDSAY",	"Lindsay",
	"LN",	"lane",
	"LNS",	"lanes",
	"LOOP",	"loop",
	"LOSB",	"low surface brightness",
	"LSB",	"low surface brightness",
	"M",	"much",
	"MANY",	"many",
	"MATCH",	"match",
	"MOTTLED",	"mottled",
	"MULT",	"multiple",
	"MW",	"milky way",
	"N",	"narrow|north",
	"N&F",	"north&following",
	"N&P",	"north&preceding",
	"N&S",	"north&south",
	"NBAR",	"narrow bar",
	"NEAR",	"near",
	"NEB",	"nebula",
	"NEBULOUS",	"nebulous",
	"NEND",	"north end",
	"NF",	"north following",
	"NF DC",	"not found (Carlsen 1940)",
	"NF S",	"not found (Sulentic)",
	"NFO",	"north following",
	"NO",	"no|north",
	"NO CL",	"no cluster",
	"NO CL S",	"no cluster (Sulentic)",
	"NOCL",	"no cluster",
	"NONUC",	"no nucleus",
	"NORTH",	"north",
	"NP",	"north preceding",
	"NPR",	"north preceding",
	"NR",	"near(ly)",
	"NUC",	"nucleus",
	"NUCLEUS",	"nucleus",
	"O",	"open",
	"OBJ",	"object",
	"OBJECT",	"object",
	"OBSC",	"obscure(ing)",
	"OF",	"of",
	"OFF",	"off",
	"ON",	"on",
	"OR",	"or",
	"OUT",	"outer",
	"OUTER",	"outer",
	"OV",	"oval",
	"OVAL",	"oval",
	"P",	"poor(ly)|preceding",
	"P ",	"preceding",
	"PR",	"preceding",
	"PAIR",	"pair",
	"PART",	"part",
	"PCH",	"patch",
	"PCHY",	"patchy",
	"PCHS",	"patches",
	"PD",	"poorly defined",
	"PEC",	"peculiar",
	"PER",	"peripheral, periphery",
	"PERIP",	"periphery",
	"PERIPH",	"periphery",
	"PLUME",	"plume",
	"POOR",	"poor",
	"POSSIBLE",	"possible",
	"PRINT",	"print",
	"R",	"round",
	"RECT",	"rectangular",
	"REGION",	"region",
	"RESOLVED",	"resolved",
	"RG",	"ring",
	"RI",	"rich",
	"RICH",	"rich",
	"RNG",	"ring",
	"RING",	"ring",
	"S",	"south",
	"S&F",	"south&following",
	"S&N",	"south&north",
	"S&P",	"south&preceding",
	"S,",	"spiral;",
	"SB",	"barred spiral",
	"SBC",	"SBc type galaxy",
	"SBM",	"suddenly brighter toward center",
	"SC",	"Sc type galaxy",
	"SEND",	"south end",
	"SEV",	"several",
	"SF",	"south following",
	"SFO",	"south following",
	"SHAPE",	"shape",
	"SHORT",	"short",
	"SIDE",	"side",
	"SL",	"slight(ly)",
	"SLDIF",	"slightly diffuse",
	"SLEL",	"slightly elongated",
	"SM",	"small",
	"SMBM",	"suddenly much brighter toward center",
	"SO)",	"S0 galaxy",
	"SOUTH",	"south",
	"SP",	"south preceding",
	"SPIRAL",	"spiral",
	"SPN",	"spindle",
	"SPR",	"south preceding",
	"SQUARE",	"square",
	"SST",	"spiral structure",
	"SSTR",	"spiral structure",
	"STE",	"stellar",
	"STEL",	"stellar",
	"STELLAR",	"stellar",
	"STR",	"structure",
	"STRLESS",	"structureless",
	"STRUCTURE",	"structure",
	"STRUCTURELESS",	"structureless",
	"SUP",	"superimposed",
	"SUS",	"suspected",
	"SUSP",	"suspected",
	"SV",	"several",
	"SYST",	"system",
	"THIN",	"thin",
	"TIDAL",	"tidal",
	"TIW",	"tightly wound",
	"TO",	"to",
	"TRIPLE",	"triple",
	"U",	"uniform",
	"UNIF",	"uniform",
	"USB",	"uniform surface brightness",
	"V",	"very",
	"VB",	"very bright",
	"VF",	"very faint",
	"VFL",	"very flat",
	"VIS",	"visible",
	"VISIBLE",	"visible",
	"W/",	"with",
	"W/O",	"without",
	"WD",	"well defined",
	"WI",	"with",
	"WINGS",	"wings",
	"WIO",	"without",
	"WK",	"weak",
	"WO",	"without",
	"WPD",	"warped",
	0,	0
};
/*&
	"ST9",	"stars from the 9th magnitude downward",
	"ST9...13",	"stars from 9th to 13th magnitude",
	"()",	"items questioned by Dreyer enclosed in parentheses",
	*10	star of 10th mag
	"*",	"a star (or stars)",
	"**",	"double star",
	"***",	"triple star",
*/
