<$NXM/$objtype/mkfile

LIB=$NXM/$objtype/lib/libmach.a
FILES=\
	executable\
	map\
	obj\
	swap\
	sym\
	access\
	machdata\
	setmach\
	v\
	k\
	u\
	q\
	2\
	5\
	6\
	7\
	8\
	vdb\
	kdb\
	udb\
	qdb\
	2db\
	5db\
	7db\
	8db\
	vobj\
	kobj\
	uobj\
	2obj\
	5obj\
	6obj\
	7obj\
	8obj\
	qobj\
	vcodas\

HFILES=$NXM/sys/include/mach.h elf.h obj.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	$NXM/386/lib/libmach.a\
	$HFILES\
	$CFILES\

<$NXM/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -I/sys/src/cmd -I$NXM

2obj.$O: $NXM/sys/src/cmd/2c/2.out.h
5obj.$O: $NXM/sys/src/cmd/5c/5.out.h
6obj.$O: $NXM/sys/src/cmd/6c/6.out.h
7obj.$O: $NXM/sys/src/cmd/7c/7.out.h
8obj.$O: $NXM/sys/src/cmd/8c/8.out.h
kobj.$O: $NXM/sys/src/cmd/kc/k.out.h
qobj.$O: $NXM/sys/src/cmd/qc/q.out.h
uobj.$O: uc/u.out.h
vobj.$O: $NXM/sys/src/cmd/vc/v.out.h
