</$objtype/mkfile

LIB=usb.a$O
OFILES=\
	dev.$O\
	dump.$O\
	parse.$O\

HFILES=\
	usb.h\

UPDATE=\
	$HFILES\
	${OFILES:%.$O=%.c}\
	mkfile\

</sys/src/cmd/mklib

install:V:	$LIB
	date
safeinstall:V: install
safeinstallall:V: installall
nuke:V:
	rm -f *.[$OS] y.tab.? y.output y.error *.a[$OS]
