/* automatically generated by mksys */
extern char Ebadarg[]; /* bad arg in system call */
extern char Ebadchar[]; /* bad character in file name */
extern char Ebadctl[]; /* bad process or channel control request */
extern char Ebadexec[]; /* exec header invalid */
extern char Ebadfd[]; /* fd out of range or not open */
extern char Ebadip[]; /* bad ip address syntax */
extern char Ebadsharp[]; /* unknown device in # filename */
extern char Ebadspec[]; /* bad attach specifier */
extern char Ebadstat[]; /* malformed stat buffer */
extern char Ebadusefd[]; /* inappropriate use of fd */
extern char Ecmdargs[]; /* wrong #args in control message */
extern char Econinuse[]; /* connection in use */
extern char Econrefused[]; /* connection refused */
extern char Edirseek[]; /* seek in directory */
extern char Eexist[]; /* file already exists */
extern char Efilename[]; /* file name syntax */
extern char Egreg[]; /* ken has left the building */
extern char Ehungup[]; /* i/o on hungup channel */
extern char Eintr[]; /* interrupted */
extern char Einuse[]; /* device or object already in use */
extern char Eio[]; /* i/o error */
extern char Eioload[]; /* i/o error in demand load */
extern char Eisdir[]; /* file is a directory */
extern char Eismtpt[]; /* is a mount point */
extern char Eisstream[]; /* seek on a stream */
extern char Emount[]; /* inconsistent mount */
extern char Emountrpc[]; /* mount rpc error */
extern char Emouseset[]; /* mount rpc error */
extern char Enegoff[]; /* negative i/o offset */
extern char Enoattach[]; /* mount/attach disallowed */
extern char Enochild[]; /* no living children */
extern char Enocreate[]; /* mounted directory forbids creation */
extern char Enodev[]; /* no free devices */
extern char Enoerror[]; /* no error */
extern char Enofd[]; /* no free file descriptors */
extern char Enomem[]; /* kernel allocate failed */
extern char Enonexist[]; /* file does not exist */
extern char Enoport[]; /* network port not available */
extern char Enoreg[]; /* process has no saved registers */
extern char Enoswap[]; /* swap space full */
extern char Enotdir[]; /* not a directory */
extern char Enovmem[]; /* virtual memory allocation failed */
extern char Eperm[]; /* permission denied */
extern char Eprocdied[]; /* process exited */
extern char Eshort[]; /* i/o count too small */
extern char Eshortstat[]; /* stat buffer too small */
extern char Eshutdown[]; /* device shut down */
extern char Esoverlap[]; /* segments overlap */
extern char Etimedout[]; /* connection timed out */
extern char Etoobig[]; /* read or write too large */
extern char Etoosmall[]; /* read or write too small */
extern char Eunion[]; /* not in union */
extern char Eunmount[]; /* not mounted */
