</$objtype/mkfile

TARG=1l
OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../2c/2.out.h\

BIN=/$objtype/bin
</sys/src/cmd/mkone

enam.$O:	../2c/enam.c
	$CC $CFLAGS ../2c/enam.c
