</$objtype/mkfile

# default domain for faces, overridden by $facedom
DEFAULT="astro"

TARG=faces

OFILES=main.$O\
	facedb.$O\
	plumb.$O\
	util.$O\

HFILES=faces.h\

BIN=/$objtype/bin

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
CFLAGS=$CFLAGS '-DDEFAULT='$DEFAULT

$O.dblook: dblook.$O facedb.$O util.$O
	$LD -o $target $prereq
