ARCH=\
	fs\
	fs64\
	9netics32.16k\
	9netics64.8k\
	choline\
	emelie\

all:V:
	for(i in $ARCH)@{
		cd $i
		mk
	}

installall install:V:
	for(i in $ARCH) @{
		cd $i
		mk install
	}

clean:V:
	for(i in $ARCH) @{
		cd $i
		mk clean
	}
