</$objtype/mkfile

TARG=ibuddy
OFILES=main.$O
LIBDOFILES=ibuddy.$O
HFILES=\
	../lib/usb.h\
	ibuddy.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\

BIN=/$objtype/bin/usb


UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

$LIBD:V: $LIBDOFILES
	ar vu $LIBD $newprereq
	rm $newprereq

