MKSHELL=rc
<$NXM/$objtype/mkfile

TARG=\
	bitsyload\
	pencal\
	prompter\
	keyboard\
	light\
	params\

BIN=$NXM/$objtype/bin/bitsy
<$NXM/sys/src/cmd/mkmany

light.$O:V:
	# nothing

$O.light: light.rc
	cp light.rc $target

light.install:
	cp light.rc $BIN/light
