</$objtype/mkfile

TARG=mapd 
LIB=libmap/libmap.a$O
OFILES=map.$O\
	symbol.$O\
	index.$O\
	sqrt.$O\

HFILES=map.h\
	iplot.h\

BIN=/$objtype/bin/aux


</sys/src/cmd/mkone

$O.out:V:	$OFILES $LIB
	$LD $LDFLAGS -o $target $prereq

$LIB:V:
	cd libmap
	mk install

installall:V:
	for(objtype in $CPUS)
		mk install
	cp map.rc /rc/bin/map
	cp mapdemo.rc /rc/bin/mapdemo

clean nuke:V:
	@{ cd libmap; mk $target }
	rm -f *.[$OS] [$OS].out y.tab.? y.debug y.output $TARG
