</$objtype/mkfile

TARG=usbaudio
OFILES=\
	audiofs.$O\
	audiosub.$O\
	usbaudio.$O\
	usbaudioctl.$O\

HFILES=\
	usbaudio.h\
	usbaudioctl.h\
	../lib/usb.h\

UPDATE=\
	$HFILES\
	${OFILES:%.$O=%.c}\
	mkfile\
	/sys/man/3/usb\

LIB=../lib/usb.a$O

BIN=/$objtype/bin/usb
</sys/src/cmd/mkone

CFLAGS=-I../lib $CFLAGS

$LIB:
	cd ../lib
	mk install
	mk clean
