</$objtype/mkfile

TARG=ipconfig\

OFILES=\
	main.$O\
	ipv6.$O\
	ppp.$O\

HFILES=\
	../dhcp.h\
	../icmp.h\
	ipconfig.h\
	/sys/include/ip.h\

BIN=/$objtype/bin/ip

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
