</$objtype/mkfile

DIRS=9sys 9syscall fmt port $CPUS

all install:V:
	for(i in 9sys 9syscall fmt port $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS install
	}

clean:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS clean
	}

nuke:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS nuke
	}

update:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS update
	}
	update $UPDATEFLAGS /386/lib/libc.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[012456789kqvxz]
	for(objtype in 68000 68020 arm alpha 386 sparc power mips)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[012456789kqvxz]
