</$objtype/mkfile

TARG=2c
OFILES=\
	cgen.$O\
	reg.$O\
	txt.$O\
	peep.$O\
	swt.$O\
	sgen.$O\
	list.$O\
	enam.$O\
	mul.$O\

HFILES=\
	gc.h\
	2.out.h\
	../cc/cc.h\

LIB=../cc/cc.a$O

BIN=/$objtype/bin
</sys/src/cmd/mkone

$LIB:
	cd ../cc
	mk install
	mk clean

%.$O: ../cc/%.c
	$CC $CFLAGS ../cc/$stem.c

