MKSHELL=rc
<$NXM/$objtype/mkfile

PROTO=\
	mount3.$O\
	nfs3.$O\
	portmap.$O\

OFILES=\
	authunix.$O\
	client.$O\
	emalloc.$O\
	error.$O\
	fd.$O\
	fmt.$O\
	net.$O\
	prog.$O\
	rpc.$O\
	server.$O\
	suncall.$O\
	udp.$O\
	$PROTO\

HFILES=\
	$NXM/sys/include/sunrpc.h\

LIB=$NXM/$objtype/lib/libsunrpc.a

<$NXM/sys/src/cmd/mksyslib

mount3.$O: $NXM/sys/include/nfs3.h
