</sys/doc/fonts

sam.ps:D:	sam.ms fig1.ps fig2.ps fig3.ps fig4.ps fig5.pic fig6.pic fig7.pic refs
	{echo $FONTS; cat sam.ms refs} | pic | tbl | troff -ms -mpictures | lp -dstdout >sam.ps
	../cleanps sam.ps

sam.trout:D:	sam.ms fig1.ps fig2.ps fig3.ps fig4.ps fig5.pic fig6.pic fig7.pic refs
	{echo $FONTS; cat sam.ms refs} | pic | tbl | troff -ms -mpictures >sam.trout

sam.tut.out:D:	sam.tut
	troff -ms sam.tut > sam.tut.out

sam.html:D:	sam.ms fig1.ps fig2.ps fig3.ps fig4.ps fig5.pic fig6.pic fig7.pic refs
	{echo $FONTS; cat sam.ms refs} | pic | tbl | ms2html >sam.html
