extern Path*	addelem(Path **pp, Memblk *f);
extern daddrt	addrofref(daddrt refaddr, int idx);
extern void	afree(Alloc *a, void *nd);
extern int	allowed(int uid);
extern int	allowed(int);
extern int	allowed(int);
extern void*	anew(Alloc *a);
extern void	changed(Memblk *b);
extern void	checktag(u64int tag, uint type, daddrt addr);
extern char*	cliworker9p(void *v, void**aux);
extern Path*	clonepath(Path *p);
extern void	consinit(void);
extern void	consprint(char *fmt, ...);
extern void	consprintclients(void);
extern long	consread(char *buf, long count);
extern long	conswrite(char *ubuf, long count);
extern void	countfidrefs(void);
extern void	countfidrefs(void);
extern void	countfidrefs(void);
extern Memblk*	dballoc(uint type);
extern Memblk*	dbdup(Memblk *b);
extern Memblk*	dbget(uint type, daddrt addr);
extern daddrt	dbgetref(daddrt addr);
extern daddrt	dbput(Memblk *b, int type, daddrt addr);
extern long	dbread(Memblk *b);
extern void	dbsetref(daddrt addr, int ref);
extern long	dbwrite(Memblk *b);
extern void	debug(void);
extern void	dfaccessok(Memblk *f, int uid, int bits);
extern ulong	dfbno(Memblk *f, uvlong off, ulong *boffp);
extern void	dfcattr(Memblk *f, int op, char *name, void *val, long count);
extern void	dfchanged(Path *p, int muid);
extern uvlong	dfchdentry(Memblk *d, u64int addr, u64int naddr, int mkit);
extern Memblk*	dfchild(Memblk *f, int n);
extern void	dfcountfree(void);
extern long	dfcountrefs(Memblk *f);
extern Memblk*	dfcreate(Memblk *parent, char *name, int uid, ulong mode);
extern void	dfdropblks(Memblk *f, ulong bno, ulong bend);
extern int	dfdump(Memblk *f, int isdisk);
extern int	dffreeze(Memblk *f);
extern Path*	dflast(Path **pp, int nth);
extern void	dflink(Memblk *d, Memblk *f);
extern Path*	dfmelt(Path **pp, int nth);
extern ulong	dfpread(Memblk *f, void *a, ulong count, uvlong off);
extern int	dfput(Memblk *f);
extern ulong	dfpwrite(Memblk *f, void *a, ulong count, uvlong *off);
extern long	dfrattr(Memblk *f, char *name, void *val, long count);
extern void	dfremove(Memblk *p, Memblk *f);
extern Blksl	dfslice(Memblk *f, ulong len, uvlong off, int iswr);
extern void	dfused(Path *p);
extern Memblk*	dfwalk(Memblk *d, char *name, int iswr);
extern long	dfwattr(Memblk *f, char *name, void *val, long nval);
extern Path*	dropelem(Path **pp);
extern void	dumpfids(void);
extern void	dumplockstats(void);
extern void	dupdentries(void *p, int n);
extern ulong	embedattrsz(Memblk *f);
extern void	fatal(char *fmt, ...);
extern void	fidattach(Fid *fid, char *aname, char *uname);
extern Fid*	fidclone(Cli *cli, Fid *fid, int no);
extern void	fidclose(Fid *fid);
extern void	fidcreate(Fid *fid, char *name, int mode, ulong perm);
extern void	fidopen(Fid *fid, int mode);
extern long	fidread(Fid *fid, void *data, ulong count, vlong offset, Packmeta pack);
extern void	fidremove(Fid *fid);
extern void	fidwalk(Fid *fid, char *wname);
extern long	fidwrite(Fid *fid, void *data, ulong count, uvlong *offset);
extern void	followmelted(Memblk **fp, int iswr);
extern void	freerpc(Rpc *rpc);
extern int	fscheck(void);
extern uvlong	fsdiskfree(void);
extern void	fsdump(int full, int disktoo);
extern void	fsfmt(char *dev);
extern int	fsfull(void);
extern int	fslru(void);
extern uvlong	fsmemfree(void);
extern void	fsopen(char *dev);
extern void	fspolicy(void);
extern int	fsreclaim(void);
extern void	fssync(void);
extern void	fssyncproc(void*);
extern Fid*	getfid(void* clino, int no);
extern void	gmeta(Memblk *f, void *buf, ulong nbuf);
extern void	isfile(Memblk *f);
extern void	ismelted(Memblk *b);
extern int	isro(Memblk *f);
extern void	isrwlocked(Memblk *f, int iswr);
extern int	ixcallfmt(Fmt *fmt);
extern uint	ixpack(IXcall *f, uchar *ap, uint nap);
extern uint	ixpackedsize(IXcall *f);
extern char*	ixstats(char *s, char *e, int clr);
extern char*	ixstats(char *s, char*, int);
extern char*	ixstats(char *s, char*, int);
extern uint	ixunpack(uchar *ap, uint nap, IXcall *f);
extern int	leader(int gid, int lead);
extern void	lockstats(int on);
extern Memblk*	mballoc(daddrt addr);
extern int	mbcountref(Memblk *b);
extern int	mbfmt(Fmt *fmt);
extern Memblk*	mbget(int type, daddrt addr, int mkit);
extern Memblk*	mbhash(Memblk *b);
extern void	mbput(Memblk *b);
extern void	mbunhash(Memblk *b, int isreclaim);
extern void	mbunused(Memblk *b);
extern void	meltedref(Memblk *rb);
extern void	meltfids(void);
extern void	meltfids(void);
extern void	meltfids(void);
extern int	member(int uid, int member);
extern int	member(int uid, int member);
extern int	member(int uid, int member);
extern List	mfilter(List *bl, int(*f)(Memblk*));
extern void	mlistdump(char *tag, List *l);
extern void	munlink(List *l, Memblk *b, int isreclaim);
extern Fid*	newfid(void* clino, int no);
extern Path*	newpath(Memblk *root);
extern Rpc*	newrpc(void);
extern char*	ninestats(char *s, char *e, int clr);
extern char*	ninestats(char *s, char*, int);
extern char*	ninestats(char *s, char*, int);
extern void	nodebug(void);
extern void	ownpath(Path **pp);
extern int	pathfmt(Fmt *fmt);
extern ulong	pmeta(void *buf, ulong nbuf, Memblk *f);
extern void	putcli(Cli *cli);
extern void	putfid(Fid *fid);
extern void	putpath(Path *p);
extern void	quiescent(int y);
extern void	rahead(Memblk *f, uvlong offset);
extern void	replied(Rpc *rpc);
extern void	rlsedebug(int r);
extern int	rpcfmt(Fmt *fmt);
extern void	rwlock(Memblk *f, int iswr);
extern void	rwunlock(Memblk *f, int iswr);
extern void	rwusers(Memblk *uf);
extern void	rwusers(Memblk*);
extern void	rwusers(Memblk*);
extern int	setdebug(void);
extern void	setfiduid(Fid *fid, char *uname);
extern char*	tname(int t);
extern char*	updatestats(int clr);
extern int	usrfmt(Fmt *fmt);
extern int	usrid(char *n);
extern int	usrid(char*);
extern int	usrid(char*);
extern char*	usrname(int uid);
extern char*	usrname(int);
extern char*	usrname(int);
extern void	wahead(Memblk *f);
extern int	writedenied(int uid);
extern void	written(Memblk *b);
extern void	xqlock(QLock *q);
extern void	xqunlock(QLock *q);
extern void	xrwlock(RWLock *rw, int iswr);
extern void	xrwunlock(RWLock *rw, int iswr);
extern long 	wname(Memblk *f, void *buf, long len);
