ARCH=\
	alphapc\
	bitsy\
	kw\
	mtx\
	omap\
	pc\
	ppc\
	teg2\
	
all:V:
	for(i in $ARCH)@{
		cd $i
		mk
	}

installall install:V:
	for(i in $ARCH) @{
		cd $i
		mk install
	}

clean:V:
	for(i in $ARCH) @{
		cd $i
		mk clean
	}
