MKSHELL=rc
<$NXM/$objtype/mkfile

LIB=$NXM/$objtype/lib/libauthsrv.a
OFILES=\
	_asgetticket.$O\
	_asrdresp.$O\
	authdial.$O\
	convA2M.$O\
	convM2A.$O\
	convM2PR.$O\
	convM2T.$O\
	convM2TR.$O\
	convPR2M.$O\
	convT2M.$O\
	convTR2M.$O\
	nvcsum.$O\
	opasstokey.$O\
	passtokey.$O\
	readnvram.$O\

HFILES=\
	$NXM/sys/include/authsrv.h\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:$NXM/$objtype/%=/386/%}\

<$NXM/sys/src/cmd/mksyslib
