.TH ACCESS 1 "4 January 1998" "Kpathsea @VERSION@"
.\"=====================================================================
.if n .ds MP MetaPost
.if t .ds MP MetaPost
.if n .ds MF Metafont
.if t .ds MF M\s-2ETAFONT\s0
.if t .ds TX \fRT\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X\fP
.if n .ds TX TeX
.ie t .ds OX \fIT\v'+0.25m'E\v'-0.25m'X\fP\" for troff
.el .ds OX TeX\" for nroff
.\" the same but obliqued
.\" BX definition must follow TX so BX can use TX
.if t .ds BX \fRB\s-2IB\s0\fP\*(TX
.if n .ds BX BibTeX
.\" LX definition must follow TX so LX can use TX
.if t .ds LX \fRL\\h'-0.36m'\\v'-0.15v'\s-2A\s0\\h'-0.15m'\\v'0.15v'\fP\*(TX
.if n .ds LX LaTeX
.\"=====================================================================
.SH NAME
access \- determine whether a file can be accessed
.SH SYNOPSIS
.B access
.I -mode
.I file
.\"=====================================================================
.SH DESCRIPTION
Exit successfully if
.I file
can be accessed with the specified mode.
.I mode
is one or more letters of
.IR rwx ,
where
.I r
is for readable,
.I w
is for writable, and
.I x
is for executable.
.PP
The difference between
.B access
and
.B test
is that the latter looks at the permission bits, while the former
checks using the
.BR access (2)
system call.  This makes a difference when file systems have been
mounted read-only.
.\"=====================================================================
.SH OPTIONS
.B access
accepts the following additional options:
.TP
.B --help
.rb
Print help message and exit.
.TP
.B --version
.rb
Print version information and exit.
.\"=====================================================================
.SH "SEE ALSO"
.BR access (2)
