#!/bin/sh
# $Id: eps2eps,v 1.1 2000/03/10 07:51:55 lpd Exp $
# "Distill" Encapsulated PostScript.

OPTIONS="-dDEVICEWIDTH=250000 -dDEVICEHEIGHT=250000"
while true
do
	case "$1" in
	-*) OPTIONS="$OPTIONS $1" ;;
	*)  break ;;
	esac
	shift
done

if [ $# -ne 2 ]; then
	echo "Usage: `basename $0` ...switches... input.eps output.eps" 1>&2
	exit 1
fi

exec gs -q -sDEVICE=epswrite -sOutputFile=$2 -dNOPAUSE -dBATCH $OPTIONS $1
