#! /bin/sh
# $Id: pdf2dsc,v 1.2 2000/05/19 06:38:25 lpd Exp $

# psf2dsc: generates an index of a PDF file.
#
# Yves Arrouye <arrouye@debian.org>, 1996.
# 2000-05-18 lpd <ghost@aladdin.com> added -dSAFER

me=`basename $0`

usage() {
    >&2 echo usage: $me "pdffile [ dscfile ]"
    exit 1
}

if [ $# -gt 2 ]
then
    usage
fi

pdffile=$1
dscfile=$2
: ${dscfile:=`echo $pdffile | sed 's,\.[^/.]*,,'`.dsc}

exec gs -q -dNODISPLAY -dSAFER \
    -sPDFname="$pdffile" -sDSCname="$dscfile" pdf2dsc.ps -c quit
