#!/bin/sh
# $Id: pdfopt,v 1.2 2000/05/30 05:28:22 lpd Exp $
# Convert PDF to "optimized" form.

OPTIONS=""
while true
do
	case "$1" in
	-*) OPTIONS="$OPTIONS $1" ;;
	*)  break ;;
	esac
	shift
done

if [ $# -ne 2 ]; then
	echo "Usage: `basename $0` input.pdf output.pdf" 1>&2
	exit 1
fi

exec gs -q -dNODISPLAY -dSAFER $OPTIONS -- pdfopt.ps $1 $2
