#!/bin/sh
# $Id: pf2afm,v 1.1 2000/03/09 08:40:40 lpd Exp $
# Make an AFM file from PFB / PFA and (optionally) PFM files.  Usage:
#	pf2afm fontfilename
# Output goes to fontfilename.afm, which must not already exist.
# See pf2afm.ps for more details.

exec gs -q -dNODISPLAY -- pf2afm.ps "$@"
