#!/bin/sh
# $Id: pfbtopfa,v 1.2 2000/04/12 17:41:41 lpd Exp $
# Convert .pfb fonts to .pfa format

if [ $# -eq 2 ] 
then
    outfile=$2
elif [ $# -eq 1 ]
then
    outfile=`basename $1 \.pfb`.pfa
else
    echo "Usage: `basename $0` input.pfb [output.pfa]" 1>&2
    exit 1
fi

exec gs -q -dNODISPLAY -- pfbtopfa.ps $1 $outfile
