#!/bin/sh
# $Id: ps2pdfwr,v 1.1 2000/03/09 08:40:40 lpd Exp $
# Convert PostScript to PDF without specifying CompatibilityLevel.

OPTIONS=""
while true
do
	case "$1" in
	-?*) OPTIONS="$OPTIONS $1" ;;
	*)  break ;;
	esac
	shift
done

if [ $# -lt 1 -o $# -gt 2 ]; then
	echo "Usage: `basename $0` [options...] (input.ps|-) [output.pdf|-]" 1>&2
	exit 1
fi

infile=$1;

if [ $# -eq 1 ]
then
	case "${infile}" in
	  -)		outfile=- ;;
	  *.ps)		base=`basename ${infile} .ps`; outfile=${base}.pdf ;;
	  *)		base=`basename ${infile}`; outfile=${base}.pdf ;;
	esac
else
	outfile=$2
fi

# Doing an initial 'save' helps keep fonts from being flushed between pages.
# We have to include the options twice because -I only takes effect if it
# appears before other options.
exec gs $OPTIONS -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$outfile $OPTIONS -c save pop -f $infile
