</$objtype/mkfile

TARG=4a
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../4c/4.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

BIN=/$objtype/bin
< /sys/src/cmd/mkone
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
