load("//sys/src/FLAGS", "KLIB_COMPILER_FLAGS", "LIB_COMPILER_FLAGS")

cc_library(
    name = "all",
    copts=KLIB_COMPILER_FLAGS,
    includes=[
        "//sys/include",
        "//amd64/include",
    ],
    srcs=[
        "eipfmt.c",
        "equivip.c",
        "parseip.c",
        "parseether.c",
        "myetheraddr.c",
        "myipaddr.c",
        "classmask.c",
        "bo.c",
        "readipifc.c",
        "ipaux.c",
        "ptclbsum.c",
    ],
)

cc_library(
    name = "all",
    copts=LIB_COMPILER_FLAGS,
    includes=[
        "//sys/include",
        "//amd64/include",
    ],
    srcs=[
        "eipfmt.c",
        "equivip.c",
        "parseip.c",
        "parseether.c",
        "myetheraddr.c",
        "myipaddr.c",
        "classmask.c",
        "bo.c",
        "readipifc.c",
        "ipaux.c",
        "ptclbsum.c",
    ]
)
