<$ROOT/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libip.a
OFILES=\
	eipfmt.$O\
	equivip.$O\
	parseip.$O\
	parseether.$O\
	myetheraddr.$O\
	myipaddr.$O\
	classmask.$O\
	bo.$O\
	readipifc.$O\
	ipaux.$O\
	ptclbsum.$O\

HFILES=\
	$ROOT/sys/include/ip.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

<$ROOT/sys/src/cmd/mksyslib
