</$objtype/mkfile

TARG=	fs\

OFILES=\
	fs.$O\
	imap4.$O\
	mbox.$O\
	plan9.$O\
	pop3.$O\
	strtotm.$O\

LIB=../common/libcommon.a$O\

HFILES= ../common/common.h\
	dat.h

BIN=/$objtype/bin/upas

UPDATE=\
	mkfile\
	${TARG:%=/386/bin/upas/%}\
	${TARG:%=%.c}\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone
CFLAGS=$CFLAGS -I/sys/include -I../common
