</$objtype/mkfile

TARG=	fs\
	biff\

LIB=../common/libcommon.a$O\

HFILES= ../common/common.h\
	dat.h

BIN=/$objtype/bin/upas
</sys/src/cmd/mkmany
CFLAGS=$CFLAGS -I/sys/include -I../common


FSOFILES=\
	imap4.$O\
	mbox.$O\
	plan9.$O\
	pop3.$O\
	strtotm.$O\

$O.fs:	$FSOFILES

safeinstallall:V:
	for(objtype in $CPUS)
		mk $MKFLAGS safeinstall

safeinstall:V:
	mv $BIN/fs $BIN/_fs
	mk install


