/*
 * minikernel fns
 */
void	biogetdev(int);
int	bioread(void*, long, int);
void	boot(ulong);
int	cangetc(IOQ*);
int	canputc(IOQ*);
void	dcflush(void *, int);
void	delay(int);
void	devinit(void);
void	*dmaalloc(ulong);
void	exit(void);
long	findpart(char*);
void	firmware(void);
int	getc(IOQ*);
int	getstr(char*, char*, int, char*, int);
void	*ialloc(ulong, int);
void	icflush(void *, int);
void	initq(IOQ*);
void	iobufinit(void);
void	kbdinit(void);
void	kbdintr(void);
void	panic(char *, ...);
int	putc(IOQ*, int);
void	puttlbx(int, ulong, ulong);
int	setcolor(ulong, ulong, ulong, ulong);
void	sccsetup(void*, ulong);
void	sccintr(void);
void	sccspecial(int, IOQ*, IOQ*, int);
void	sccputc(IOQ*, int);
void	screeninit(int);
void	screenputc(int);
void	screenputs(char*, int);
int	scsicap(int, void*);
Scsi	*scsicmd(int, int, long);
int	scsiexec(Scsi*, int);
void	scsiintr(void);
int	scsiready(int);
void	scsireset(void);
int	scsisense(int, void*);
int	splhi(void);
int	spllo(void);
void	splx(int);
void	tlbinit(void);
void	ttyscreen(void);
void	vecinit(void);
void	vector80(void);
void	wbflush(void);
