</$objtype/mkfile

TARG=9660srv

OFILES=\
	main.$O\
	9660srv.$O\
	xfile.$O\
	iobuf.$O\
	data.$O\

HFILES=dat.h fns.h
BIN=/$objtype/bin

UPDATE=\
	mkfile\
	/sys/man/4/dossrv\
	/386/bin/$TARG\
	${OFILES:%.$O=%.c}\
	$HFILES\

</sys/src/cmd/mkone

$O.out:

9660srv.$O: iso9660.h
