void error(void);
void scanargs(void);
void initialize(void);
void openinput(void);
boolean inputln(textfile f);
void printid(namepointer p);
namepointer idlookup(eightbits t);
namepointer modlookup(sixteenbits l);
namepointer prefixlookup(sixteenbits l);
void storetwobytes(sixteenbits x);
void pushlevel(namepointer p);
void poplevel(void);
sixteenbits getoutput(void);
void flushbuffer(void);
void appval(integer v);
void sendout(eightbits t,sixteenbits v);
void sendsign(integer v);
void sendval(integer v);
void sendtheoutput(void);
boolean linesdontmatch(void);
void primethechangebuffer(void);
void checkchange(void);
void getline(void);
eightbits controlcode(ASCIIcode c);
eightbits skipahead(void);
void skipcomment(void);
eightbits getnext(void);
void scannumeric(namepointer p);
void scanrepl(eightbits t);
void definemacro(eightbits t);
void scanmodule(void);
