MKSHELL=rc
<$NXM/$objtype/mkfile

LIB=$NXM/$objtype/lib/libavl.a
OFILES=\
	avl.$O\

HFILES=$NXM/sys/include/avl.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:$NXM/$objtype/%=/386/%}\

<$NXM/sys/src/cmd/mksyslib
