</$objtype/mkfile

LIB=cc.a$O
OFILES=\
	y.tab.$O\
	lex.$O\
	mpatof.$O\
	mac.$O\
	dcl.$O\
	acid.$O\
	com.$O\
	con.$O\
	sub.$O\
	com64.$O\
	compat.$O\

HFILES=cc.h\
	y.tab.h\

YFILES=cc.y\

</sys/src/cmd/mklib

install:V:	$LIB
	date

$LIB:	$LIBOBJ
	ar vu $LIB $OFILES

mac.$O:	macbody

everything:V:
	# mk the current compilers
	for(DIR in cc vc 2c kc 8c){
		cd ../$DIR
		mk nuke
		mk install
	}
	# mk all the others with those
	for(DIR in cc vc 2c kc 8c){
		cd ../$DIR
		mk nuke
		mk installall
		mk clean
	}
