.ds dQ /usr/lib/postscript
.TH POSTDMD 1
.SH NAME
.B postdmd
\- PostScript translator for
.SM DMD
bitmap files
.SH SYNOPSIS
\*(mBpostdmd\f1
.OP "" options []
.OP "" files []
.SH DESCRIPTION
.B postdmd
translates
.SM DMD
bitmap
.IR files ,
as produced by
.BR dmdps ,
or
.I files
written in the Ninth Edition
.BR bitfile (9.5)
format
into PostScript and writes the results on the
standard output.
If no
.I files
are specified, or if
.OP \-
is one of the input
.IR files ,
the standard input is read.
The following
.I options
are understood:
.TP 0.75i
.OP \-b num
Pack the bitmap in the output file using
.I num
byte patterns.
A value of 0 turns off all packing of the output file.
By default
.I num
is 6.
.TP
.OP \-c num
Print
.I num
copies of each page.
By default only one copy is printed.
.TP
.OP \-f
Flip the sense of the bits in
.I files
before printing the bitmaps.
.TP
.OP \-m num
Magnify each logical page by the factor
.IR num .
Pages are scaled uniformly about the origin,
which by default is located at the center of
each page.
The default magnification is 1.0.
.TP
.OP \-n num
Print
.I num
logical pages on each piece of paper,
where
.I num
can be any positive integer.
By default
.I num
is set to 1.
.TP
.OP \-o list
Print pages whose numbers are given in the comma-separated
.IR list .
The list contains single numbers
.I N
and ranges
.IR N1\-\|N2 .
A missing
.I N1
means the lowest numbered page, a missing
.I N2
means the highest.
.TP
.OP \-p mode
Print
.I files
in either \*(mBportrait\fP or \*(mBlandscape\fP
.IR mode .
Only the first character of
.I mode
is significant.
The default
.I mode
is \*(mBportrait\fP.
.TP
.OP \-u
Disables much of the unpacking for Eighth
Edition bitmap files.
Usually results in smaller output files that take longer to print.
Not a recommended option.
.TP
.OP \-x num
Translate the origin
.I num
inches along the positive x axis.
The default
coordinate system has the origin fixed at the
center of the page, with positive
x to the right and positive y up the page.
Positive
.I num
moves everything right.
The default offset is 0 inches.
.TP
.OP \-y num
Translate the origin
.I num
inches along the positive y axis.
Positive
.I num
moves everything up the page.
The default offset is 0.
.TP
.TP
.OP \-L file
Use
.I file
as the PostScript prologue.
.br
The default is
.MR \*(dQ/postdmd.ps .
.PP
Three options allow insertion of arbitrary PostScript
at controlled points in the translation process:
.TP 0.75i
.OP \-C file
Copy
.I file
to the output file;
.I file
must contain legitimate PostScript.
.TP
.OP \-P string
Include
.I string
in the output file;
.I string
must be legitimate PostScript.
.TP
.OP \-R action
Requests special
.I action
(e.g.,
.MR manualfeed )
on a per page or global basis.
The
.I action
string can be given as
.IR request,
.IM request : page\f1\|,
or
.IM request : page : file\f1\|.
If
.I page
is omitted or given as 0, the request applies to all pages.
If
.I file
is omitted, the request lookup is done in
.MR \*(dQ/ps.requests .
.PP
Only one bitmap is printed on each logical page, and each of the input
.I files
must contain complete descriptions of at least one bitmap.
Decreasing the pattern size using the
.OP \-b
option may help throughput on printers with fast processors
(e.g., \s-1PS\s+1-810),
while increasing the pattern size will often be the right move
on older models
(.e.g, \s-1PS\s+1-800).
.SH DIAGNOSTICS
A 0 exit status is returned if
.I files
were successfully processed.
.br
.ne 4v
.SH FILES
.MW \*(dQ/postdmd.ps
.br
.MW \*(dQ/forms.ps
.br
.MW \*(dQ/ps.requests
.SH SEE ALSO
.BR dpost (1),
.BR postdaisy (1),
.BR postio (1),
.BR postmd (1),
.BR postprint (1),
.BR postreverse (1),
.BR posttek (1)
