</$objtype/mkfile

LIB=/$objtype/lib/libndb.a
OFILES=\
	ndbhash.$O\
	ndbopen.$O\
	ndbparse.$O\
	ndbcache.$O\
	ndbcat.$O\
	ndbgetval.$O\
	ndbaux.$O\
	ndbfree.$O\
	ipattr.$O\
	ndbipinfo.$O\
	ndblookval.$O\
	csgetval.$O\
	csipinfo.$O\
	dnsquery.$O\

HFILES=/sys/include/ndb.h

</sys/src/cmd/mksyslib

$O.out: testipinfo.$O
	$LD $prereq
