#!/bin/sh -eu
#
# Copyright (C) 2018 Harvey OS
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
set -e

trap : 2

$HARVEY/util/ufs -root=$HARVEY &
ufspid=$!

export machineflag=q35
if [ "$(uname)" = "Linux" ] && [ -e /dev/kvm ]; then
	export kvmflag='-enable-kvm'
	export machineflag='pc,accel=kvm'
	if [ ! -w /dev/kvm ]; then
		# we don't have access as a regular user
		export kvmdo=sudo
	fi
fi

read -r cmd <<EOF
$kvmdo qemu-system-x86_64 -s -cpu Opteron_G1 -smp 4 -m 2048 $kvmflag \
-nographic \
--machine $machineflag \
-net nic,model=rtl8139 \
-net user,id=user.0,\
hostfwd=tcp::5555-:1522,\
hostfwd=tcp::9999-:9,\
hostfwd=tcp::17010-:17010,\
hostfwd=tcp::1666-:1666,\
hostfwd=tcp::5356-:5356,\
hostfwd=tcp::17013-:17013 \
-net dump,file=/tmp/vm0.pcap \
-append "service=cpu nobootprompt=tcp maxcores=1024 fs=10.0.2.2 auth=10.0.2.2 nvram=/boot/nvram nvrlen=512 nvroff=0 acpiirq=1" \
-kernel $HARVEY/sys/src/9/amd64/harvey.32bit $*
EOF

echo $cmd
eval $cmd

kill $ufspid
wait
