#!/bin/bash
build sys/src/9/amd64/amd64coreboot.json && \
	cp sys/src/9/amd64/harvey.32bit /var/lib/tftpboot && \
	echo "OK" &&  \
	exit


# sudo service isc-dhcp-server restart && echo "OK" && exit


echo " IT WENT WRONG"

