extern	Image		*background;
extern	Image		*bordercolor;
extern	Image		*black;
extern	Image		*blue;
extern	Image		*darkblue;
extern	Image		*darkgrey;
extern	Image		*darkgreen;
extern	Image		*darkmagenta;
extern	Image		*green;
extern	Image		*grey;
extern	Image		*high;
extern	Image		*land;
extern	Image		*lightblue;
extern	Image		*lightgreen;
extern	Image		*lightgrey;
extern	Image		*lightmagenta;
extern	Image		*low;
extern	Image		*magenta;
extern	Image		*oceanblue;
extern	Image		*pale;
extern	Image		*paleblue;
extern	Image		*paleyellow;
extern	Image		*red;
extern	Image		*sea;
extern	Image		*white;
extern	Image		*yellow;

extern	Font			*romanfont, *boldfont;

void	colorinit(char*, char*);
