void	initvme(void);
void	initsql(void);
void	runvme(void);
void	runsql(void);
ulong	vmefetch(ulong);
void	vmestore(ulong, ulong);
void	vmexmit(ulong, long);
void	recvvme(void);
void	errorflush(void);
void	exits(char*);
void	delay(long);
int	fmtinstall(int, int (*)(void*, int, int, int, int));
void*	memset(void*, int, ulong);
int	print(char*, ...);
void	putc(int);
int	numbconv(void*, int, int, int, int);
void	strconv(char*, int, int, int);
char*	strchr(char*, char);
long	strlen(char*);
ulong	modpc(ulong, ulong);
void	irq5(uchar);
ulong	swapl(ulong);
void	chkabort(void);
void	bmovevf(ulong, void*);
void	bmovefv(void*, ulong);
void	duartinit(void);
void	sysctl(long, long, long);
