</$objtype/mkfile

TARG=6a
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../6c/6.out.h\
	y.tab.h\
	a.h\

YFILES=a.y

BIN=/$objtype/bin
< /sys/src/cmd/mkone
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
