</$objtype/mkfile

LIB=/$objtype/lib/libmemlayer.a

FILES=\
	draw\
	lalloc\
	layerop\
	ldelete\
	lhide\
	line\
	load\
	lorigin\
	lsetrefresh\
	ltofront\
	ltorear\
	unload\

HFILES=\
	/sys/include/memlayer.h\
	/sys/include/memdraw.h\
	/sys/include/draw.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libmemlayer.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib
