</$objtype/mkfile

SYSTEM=plan9
VERSION=3.3.1

POSTLIB=/sys/lib/postscript/prologues

TARG=postprint
OFILES=postprint.$O\

COMMONDIR=../common

HFILES=postprint.h\
	$COMMONDIR/comments.h\
	$COMMONDIR/ext.h\
	$COMMONDIR/gen.h\
	$COMMONDIR/path.h\

BIN=/$objtype/bin/aux
LIB=$COMMONDIR/com.a$O

</sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c -D$SYSTEM -D_POSIX_SOURCE -I$COMMONDIR -B

install:V:	$POSTLIB/postprint.ps

$POSTLIB/postprint.ps:	postprint.ps
	cp $prereq $target

$LIB:
	cd $COMMONDIR
	mk install
	mk clean
