objtype=riscv
</$objtype/mkfile

LIB=/$objtype/lib/libc.a
SFILES=\
	argv0.s\
	atom.s\
	cycles.s\
	getcallerpc.s\
	getfcr.s\
	main9.s\
	main9p.s\
#	memccpy.s\
#	memchr.s\
#	memcmp.s\
#	memmove.s\
#	memset.s\
	setsb.s\
	setjmp.s\
	sqrt.s\
#	strchr.s\
#	strcmp.s\
#	strcpy.s\
	tas.s\
	vlop.s\

CFILES=\
	notejmp.c\
	vlrt.c\

HFILES=/sys/include/libc.h

OFILES=${CFILES:%.c=%.$O} ${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$CFILES\
	$SFILES\

</sys/src/cmd/mksyslib
