MKSHELL=rc
<$NXM/$objtype/mkfile

TARG=kb
OFILES=main.$O
LIBDOFILES=kb.$O\
	hid.$O

HFILES=\
	../lib/usb.h\
	hid.h\

LIBD=../lib/usbdev.a$O
LIBU=../lib/usb.a$O
LIB=\
	$LIBD\
	$LIBU\

BIN=$NXM/$objtype/bin/usb


UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

<$NXM/sys/src/cmd/mkone
CFLAGS=-I../lib $CFLAGS

$LIBU:
	cd ../lib
	mk install
	mk clean

$LIBD:V: $LIBDOFILES
	ar vu $LIBD $newprereq
	rm $newprereq

