void	initthings(void);
void	drawthings(void);
void	exinit(void);
int	kbdchar(void);
void	jxystring(int, int, char*);
void	jxychar(int, int, int);
int	chartyped(void);
void	bombmove(void);
void	move(struct thing*, int, int);
int	advance(struct thing*);
int	fuzz(void);
void	kill(struct thing*);
void	process(int);
void	allover(int who);
void	gloat(void);
void	select(void);
void	attack(struct thing*);
void	exstart(int, int);
int	exmove(void);
void	exinit(void);
void	exclear(struct boom*);
void	exblob(int, int, int);
int	_min(int, int);
int	_max(int, int);
void	buzz(void);
void	calibrate(void);
