MKSHELL=rc
<$NXM/$objtype/mkfile

TARG=va
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../vc/v.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

BIN=$NXM/$objtype/bin
<$NXM/sys/src/cmd/mkone
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
