</$objtype/mkfile

TARG=ppp
OFILES=ppp.$O\
	compress.$O\
	block.$O\
	mppc.$O\
	ipaux.$O\
	thw.$O\
	thwack.$O\
	unthwack.$O\

HFILES=ppp.h\

BIN=/$objtype/bin/ip
UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

</sys/src/cmd/mkone

safeinstall: $O.out
	mv $BIN/$TARG $BIN/o$TARG
	cp $O.out $BIN/$TARG

$O.testppp: testppp.$O
	$LD -o $O.testppp $prereq
