</$objtype/mkfile

LIB=/$objtype/lib/libl.a
FILES=\
	allprint\
	main\
	reject\
	yyless\
	yywrap\

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libl.a\
	$CFILES\

</sys/src/cmd/mksyslib
