load('//sys/src/FLAGS', "LIB_COMPILER_FLAGS")

cc_library(
	name = "libcomplete",
        copts = LIB_COMPILER_FLAGS,
        includes=[
            "//sys/include"
            "//amd64/include"
        ],
	srcs = [
		"complete.c"
	]
)
