<$ROOT/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libcomplete.a
OFILES=\
	complete.$O\

HFILES=$ROOT/sys/include/complete.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

<$ROOT/sys/src/cmd/mksyslib
