.global abs
abs:
.global acidthandlers
acidthandlers:
.global _acsysret
_acsysret:
.global alt
alt:
.global _amd64_bin_auth_factotumcode
_amd64_bin_auth_factotumcode:
.global _amd64_bin_auth_factotumlen
_amd64_bin_auth_factotumlen:
.global _amd64_bin_ip_ipconfigcode
_amd64_bin_ip_ipconfigcode:
.global _amd64_bin_ip_ipconfiglen
_amd64_bin_ip_ipconfiglen:
.global atoi
atoi:
.global chancreate
chancreate:
#if 0
.global chartorune
chartorune:
#endif
.global cistrcmp
cistrcmp:
.global cistrncmp
cistrncmp:
.global cleanname
cleanname:
.global convD2M
convD2M:
.global convM2D
convM2D:
.global convM2S
convM2S:
.global convS2M
convS2M:
.global defmask
defmask:
.global dirfmt
dirfmt:
.global eipfmt
eipfmt:
.global exec
exec:
.global exits
exits:
.global fcallfmt
fcallfmt:
#if 0
.global fmtinstall
fmtinstall:
.global fmtprint
fmtprint:
.global fmtstrcpy
fmtstrcpy:
.global fmtstrflush
fmtstrflush:
.global fmtstrinit
fmtstrinit:
#endif
.global fork
fork:
.global fprint
fprint:
.global getcallerpc
getcallerpc:
.global getfields
getfields:
.global hmac_sha1
hmac_sha1:
.global hnputl
hnputl:
.global hnputs
hnputs:
.global idthandlers
idthandlers:
.global initcode
initcode:
.global IPnoaddr
IPnoaddr:
.global kerndate
kerndate:
.global maskip
maskip:
#if 0
.global memccpy
memccpy:
.global memchr
memchr:
.global memcmp
memcmp:
.global memmove
memmove:
.global memset
memset:
#endif
.global nhgetl
nhgetl:
.global nhgets
nhgets:
.global open
open:
.global parseip
parseip:
.global parseipmask
parseipmask:
.global pread
pread:
.global procrfork
procrfork:
.global qsort
qsort:
#if 0
.global quotefmtinstall
quotefmtinstall:
.global runetochar
runetochar:
#endif
.global sdfakescsi
sdfakescsi:
.global sdsetsense
sdsetsense:
.global sendp
sendp:
.global seprint
seprint:
.global sipi
sipi:
.global smprint
smprint:
.global snprint
snprint:
.global sprint
sprint:
.global ssldevtab
ssldevtab:
.global statcheck
statcheck:
.global strchr
strchr:
.global strcmp
strcmp:
.global strcpy
strcpy:
.global strdup
strdup:
.global strecpy
strecpy:
.global strlen
strlen:
.global strncmp
strncmp:
.global strncpy
strncpy:
.global strrchr
strrchr:
.global strstr
strstr:
.global strtol
strtol:
.global strtoul
strtoul:
.global strtoull
strtoull:
.global syscallentry
syscallentry:
.global sysrforkret
sysrforkret:
.global threadexits
threadexits:
.global threadexitsall
threadexitsall:
.global tokenize
tokenize:
.global touser
touser:
.global utfnlen
utfnlen:
.global utfrune
utfrune:
.global vseprint
vseprint:
.global vsnprint
vsnprint:
.global write
write:
.global xactouser
xactouser:
	ret
.global rerrstr
rerrstr:
