.global _amd64_bin_auth_factotumcode
_amd64_bin_auth_factotumcode: popq %rdi; movq $_amd64_bin_auth_factotumcode, %rsi; call badcall // ndnr
.global _amd64_bin_auth_factotumlen
_amd64_bin_auth_factotumlen: popq %rdi; movq $_amd64_bin_auth_factotumlen, %rsi; call badcall // ndnr
.global _amd64_bin_ip_ipconfigcode
_amd64_bin_ip_ipconfigcode: popq %rdi; movq $_amd64_bin_ip_ipconfigcode, %rsi; call badcall // ndnr
.global _amd64_bin_ip_ipconfiglen
_amd64_bin_ip_ipconfiglen: popq %rdi; movq $_amd64_bin_ip_ipconfiglen, %rsi; call badcall // ndnr
