/* automatically generated by mksys */
#include "u.h"
#include "../port/lib.h"
#include "mem.h"
#include "dat.h"
#include "fns.h"
#include "../../libc/9syscall/sys.h"

extern void sysr1(Ar0*, ...);
extern void sys_errstr(Ar0*, ...);
extern void sysbind(Ar0*, ...);
extern void syschdir(Ar0*, ...);
extern void sysclose(Ar0*, ...);
extern void sysdup(Ar0*, ...);
extern void sysalarm(Ar0*, ...);
extern void sysexec(Ar0*, ...);
extern void sysexits(Ar0*, ...);
extern void sys_fsession(Ar0*, ...);
extern void sysfauth(Ar0*, ...);
extern void sys_fstat(Ar0*, ...);
extern void syssegbrk(Ar0*, ...);
extern void sys_mount(Ar0*, ...);
extern void sysopen(Ar0*, ...);
extern void sysread(Ar0*, ...);
extern void sysoseek(Ar0*, ...);
extern void syssleep(Ar0*, ...);
extern void sys_stat(Ar0*, ...);
extern void sysrfork(Ar0*, ...);
extern void syswrite(Ar0*, ...);
extern void syspipe(Ar0*, ...);
extern void syscreate(Ar0*, ...);
extern void sysfd2path(Ar0*, ...);
extern void sysbrk_(Ar0*, ...);
extern void sysremove(Ar0*, ...);
extern void sys_wstat(Ar0*, ...);
extern void sys_fwstat(Ar0*, ...);
extern void sysnotify(Ar0*, ...);
extern void sysnoted(Ar0*, ...);
extern void syssegattach(Ar0*, ...);
extern void syssegdetach(Ar0*, ...);
extern void syssegfree(Ar0*, ...);
extern void syssegflush(Ar0*, ...);
extern void sysrendezvous(Ar0*, ...);
extern void sysunmount(Ar0*, ...);
extern void sys_wait(Ar0*, ...);
extern void syssemacquire(Ar0*, ...);
extern void syssemrelease(Ar0*, ...);
extern void sysseek(Ar0*, ...);
extern void sysfversion(Ar0*, ...);
extern void syserrstr(Ar0*, ...);
extern void sysstat(Ar0*, ...);
extern void sysfstat(Ar0*, ...);
extern void syswstat(Ar0*, ...);
extern void sysfwstat(Ar0*, ...);
extern void sysmount(Ar0*, ...);
extern void sysawait(Ar0*, ...);
extern void syspread(Ar0*, ...);
extern void syspwrite(Ar0*, ...);
extern void systsemacquire(Ar0*, ...);
extern void sysnsec(Ar0*, ...);
extern void sysawake(Ar0*, ...);

Systab systab[] = {
[SYSR1] { "sysr1", sysr1, { .i = -1 } },
[_ERRSTR] { "_errstr", sys_errstr, { .i = -1 } },
[BIND] { "bind", sysbind, { .i = -1 } },
[CHDIR] { "chdir", syschdir, { .i = -1 } },
[CLOSE] { "close", sysclose, { .i = -1 } },
[DUP] { "dup", sysdup, { .i = -1 } },
[ALARM] { "alarm", sysalarm, { .vl = -1ll } },
[EXEC] { "exec", sysexec, { .v = (void*)-1ll } },
[EXITS] { "exits", sysexits, { .i = -1 } },
[_FSESSION] { "_fsession", sys_fsession, { .i = -1 } },
[FAUTH] { "fauth", sysfauth, { .i = -1 } },
[_FSTAT] { "_fstat", sys_fstat, { .i = -1 } },
[SEGBRK] { "segbrk", syssegbrk, { .v = (void*)-1ll } },
[_MOUNT] { "_mount", sys_mount, { .i = -1 } },
[OPEN] { "open", sysopen, { .i = -1 } },
[READ] { "read", sysread, { .i = -1 } },
[OSEEK] { "oseek", sysoseek, { .i = -1 } },
[SLEEP] { "sleep", syssleep, { .i = -1 } },
[_STAT] { "_stat", sys_stat, { .i = -1 } },
[RFORK] { "rfork", sysrfork, { .i = -1 } },
[WRITE] { "write", syswrite, { .i = -1 } },
[PIPE] { "pipe", syspipe, { .i = -1 } },
[CREATE] { "create", syscreate, { .i = -1 } },
[FD2PATH] { "fd2path", sysfd2path, { .i = -1 } },
[BRK_] { "brk_", sysbrk_, { .v = (void*)-1ll } },
[REMOVE] { "remove", sysremove, { .i = -1 } },
[_WSTAT] { "_wstat", sys_wstat, { .i = -1 } },
[_FWSTAT] { "_fwstat", sys_fwstat, { .i = -1 } },
[NOTIFY] { "notify", sysnotify, { .i = -1 } },
[NOTED] { "noted", sysnoted, { .i = -1 } },
[SEGATTACH] { "segattach", syssegattach, { .v = (void*)-1ll } },
[SEGDETACH] { "segdetach", syssegdetach, { .i = -1 } },
[SEGFREE] { "segfree", syssegfree, { .i = -1 } },
[SEGFLUSH] { "segflush", syssegflush, { .i = -1 } },
[RENDEZVOUS] { "rendezvous", sysrendezvous, { .v = (void*)-1ll } },
[UNMOUNT] { "unmount", sysunmount, { .i = -1 } },
[_WAIT] { "_wait", sys_wait, { .i = -1 } },
[SEMACQUIRE] { "semacquire", syssemacquire, { .i = -1 } },
[SEMRELEASE] { "semrelease", syssemrelease, { .i = -1 } },
[SEEK] { "seek", sysseek, { .i = -1 } },
[FVERSION] { "fversion", sysfversion, { .i = -1 } },
[ERRSTR] { "errstr", syserrstr, { .i = -1 } },
[STAT] { "stat", sysstat, { .i = -1 } },
[FSTAT] { "fstat", sysfstat, { .i = -1 } },
[WSTAT] { "wstat", syswstat, { .i = -1 } },
[FWSTAT] { "fwstat", sysfwstat, { .i = -1 } },
[MOUNT] { "mount", sysmount, { .i = -1 } },
[AWAIT] { "await", sysawait, { .i = -1 } },
[PREAD] { "pread", syspread, { .i = -1 } },
[PWRITE] { "pwrite", syspwrite, { .i = -1 } },
[TSEMACQUIRE] { "tsemacquire", systsemacquire, { .i = -1 } },
[NSEC] { "nsec", sysnsec, { .vl = -1ll } },
[AWAKE] { "awake", sysawake, { .vl = -1ll } },

};
int nsyscall = nelem(systab);
