MKSHELL=rc
<$NXM/$objtype/mkfile

TARG=expect\
	pass\
	drain\
	at\

OFILES=

BIN=$NXM/$objtype/bin/dial

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\
	/sys/man/1/con\

<$NXM/sys/src/cmd/mkmany

