Call*	actcall(void);
void	apibutton(int, int);
char*	ascnow(void);
void	clockcruft(void);
void	dialcall(Call*);
char*	dialparse(int, char*, char*, int);
void	doalarm(void);
void	dodisplay(char*);
int	dofone(char*);
void	dotty(char*);
int	fieldparse(char*, char**, int, int);
void	flushcmd(void);
void	foneinit(void);
int	fork2(void);
Call*	getcall(char**);
int	hexcode(char**);
void	incall(Call*);
int	keyparse(char*, char*, int);
void	killproc(int);
Tm*	Localtime(long);
void	logstate(Call*, char*);
int	msgcode(char**);
void	msleep(int);
void	openfone(void);
Call*	outcall(int);
void	plumb(void);
void	putcmd(char*, ...);
int	queryinfo(char*);
void	querystart(char*);
int	readalarm(void);
int	readfone(void);
int	readtty(void);
void	sendcmd(void);
void	setapiflag(int);
void	setclock(void);
void	shcmd(char*);
void	showmsg(int, char*);
void	showstate(Call*);
void	telparse(char*);
void	xfrconf(ulong, int, char*);
