MKSHELL=rc
APE=$NXM/sys/src/ape
<$APE/config

LIB=$NXM/$objtype/lib/ape/libutf.a

OFILES=\
	rune.$O\
	runestrcat.$O\
	runestrchr.$O\
	runestrcmp.$O\
	runestrcpy.$O\
	runestrdup.$O\
	runestrlen.$O\
	runestrecpy.$O\
	runestrncat.$O\
	runestrncmp.$O\
	runestrncpy.$O\
	runestrrchr.$O\
	runestrstr.$O\
	runetype.$O\
	utfecpy.$O\
	utflen.$O\
	utfnlen.$O\
	utfrrune.$O\
	utfrune.$O\
	utfutf.$O\

HFILES=\
	$NXM/sys/include/ape/utf.h\

UPDATE=\
	mkfile\
	${OFILES:%.$O=%.c}\

<$NXM/sys/src/cmd/mksyslib

CFLAGS=-c $CFLAGS -D_POSIX_SOURCE -D_PLAN9_SOURCE -D_BSD_EXTENSION
