MKSHELL=rc
<$NXM/$objtype/mkfile

LIB=$NXM/$objtype/lib/libworker.a
OFILES=\
	worker.$O\

HFILES=$NXM/sys/include/worker.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:$NXM/$objtype/%=/386/%}\

<$NXM/sys/src/cmd/mksyslib
