MKSHELL=rc
<$NXM/$objtype/mkfile

LIBS=\
	lib9p\
	libString\
	libauth\
	libauthsrv\
	libavl\
	libbin\
	libbio\
	libc\
	libcomplete\
	libcontrol\
	libdisk\
	libdraw\
	liberror\
	libflate\
	libframe\
	libgeometry\
	libhttpd\
	libip\
	liblex\
	libmemdraw\
	libmemlayer\
	libmp\
	libndb\
	liboventi\
	libplumb\
	libregexp\
	libscribble\
	libsec\
	libseg\
	libsunrpc\
	libthread\
	libtube\
	libventi\
	libworker\

NO=	libstdio\
	libmach\

CMDS=cmd\
	games\

SUBSYS=

NOSUBSY=ape\
	/acme\

none:VQ:
	echo mk all, install, clean, nuke, release, kernels, or libs

all install clean nuke:VQ:
	date
	for (i in $LIBS $CMDS) @{
		cd $i
		echo cd $i
		mk $target
	}
	date
#	for (i in $LIBS $SUBSYS $CMDS) @{

installall:V:
	echo "installall not supported"

release:V:
	mk nuke
	rm -f $NXM/$objtype/lib/ape/*.a
	rm -f $NXM/$objtype/lib/*.a
	mk install
	mk clean

kernels:V:
	for (i in 9 boot) @{
		cd $i
		mk clean
		mk install
		mk clean
	}

libs:V:
	date
	for (i in $LIBS) @{
		cd $i
		mk clean
		mk install
		mk clean
	}
	date

cleanlibs:V:
	for (i in $LIBS) @{
		cd $i
		mk clean
	}

updatelibs:V:
	for (i in $LIBS) @{
		cd $i
		mk update
	}
