Hshtab*	addctl(Hshtab *, char);
void	assgn(Hshtab *, Value, int);
Value	btog(Value);
Node*	build(int, Node *, Node *);
void	cdl(void);
void	checkdefns(void);
void	checkfields(void);
void	checkio(Hshtab *, int);
void	clearcache(void);
void	clearmem(void);
void	clrdepend(void);
Hshtab*	comname(Hshtab *);
void	comp(Node *, int);
void	compile(int);
void	compsw(Node *, int);
void	dclbit(Hshtab *, Value);
Value	eval(Node *);
int	eval1(void);
Value	flone(Value);
Value	frone(Value);
void	getdepend(void);
void	labels(void);
Value	loadf(Hshtab *);
Hshtab*	lookup(char *, int);
int	makdigit(int, int);
void	out(Node *);
void	plaout(Node *);
void	poline(int, Value);
int	ql(int);
void	romout(Node *);
int	scanseq(int, int, int);
void	setctl(Hshtab *, char);
void	setdcused(Hshtab *, Node *);
FILE	*setinput(void);
void	setiused(Hshtab *, int);
void	setoused(Hshtab *, Node *);
void	storef(Hshtab *, Value, int);
int	subseq(int, int, int);
Value	take(Value, Value);
void	treedep(Node *);
void	treeprint(Node *);
int	vconst(Node *);
Value	vexec(Value);
void	yyerror(char *, ...);
int	yylex(void);
int	yyparse(void);
void	yyundef(Hshtab *);
void	yywarn(char *, ...);
