<$ROOT/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libgeometry.a
OFILES=\
	arith3.$O\
	matrix.$O\
	qball.$O\
	quaternion.$O\
	transform.$O\
	tstack.$O\

HFILES=$ROOT/sys/include/geometry.h

<$ROOT/sys/src/cmd/mksyslib

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

listing:V:
	pr mkfile $HFILES $CFILES|lp -du
