</$objtype/mkfile

LIB=/$objtype/lib/libgeometry.a
FILES=\
	arith3\
	matrix\
	qball\
	quaternion\
	transform\
	tstack
HFILES=/sys/include/geometry.h

</sys/src/cmd/mksyslib

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libgeometry.a\
	$HFILES\
	$CFILES\

listing:V:
	pr mkfile $HFILES $CFILES|lp -du
