</$objtype/mkfile

MAKE=mk
MAKEFILE=postscript.mk

SYSTEM=plan9
VERSION=3.3.1

ROOT=
FONTDIR=$ROOT/sys/lib/troff/font
MAN1DIR=$ROOT/tmp
POSTBIN=$ROOT/sys/lib/postscript/bin
POSTLIB=$ROOT/sys/lib/postscript/prologues


all :V: trofftable

install :V: $POSTBIN/rc/trofftable $POSTLIB/trofftable.ps $MAN1DIR/trofftable.1

installall :V: install

clean :V:
	rm -f trofftable

clobber :V: clean

$POSTBIN/rc/trofftable : trofftable
	cp $prereq $target

$POSTLIB/trofftable.ps : trofftable.ps
	cp $prereq $target

$MAN1DIR/trofftable.1 : trofftable.1
	cp $prereq $target

trofftable : trofftable.rc
	sed \
	    -e 's?^FONTDIR=.*?FONTDIR='$FONTDIR'?' \
	    -e 's?^POSTBIN=.*?POSTBIN='$POSTBIN'?' \
	    -e 's?^POSTLIB=.*?POSTLIB='$POSTLIB'?' \
	trofftable.rc >trofftable
	chmod 775 trofftable
