.ds dF /usr/lib/font
.ds dQ /usr/lib/postscript
.TH TROFFTABLE 1 "DWB 3.2"
.SH NAME
.B trofftable
\- output a PostScript program that builds a font width table
.SH SYNOPSIS
\*(mBtrofftable\f1
.OP "" options []
.OP "" shortname
.OP "" longname []
.SH DESCRIPTION
.B trofftable
writes a PostScript program on the standard output that builds a
font width table or typesetter description file.
The following
.I options
are understood:
.TP 1.0i
.OP \-t name
Use
.I name
as the template for fonts not in the default set.
Choose
.MW R
for proportionally spaced fonts and
.MW CW
for fixed width fonts.
Try
.MW ZD
(ZapfDingbats) if the font has a non-standard
character set.
The default is
.MR R .
.TP 1.0i
.OP \-C file
Copy
.I file
into each PostScript table program;
.I file
must contain legitimate PostScript.
.TP 1.0i
.OP \-H hostdir
Use
.I hostdir
as the host resident font directory.
A file in
.I hostdir
that matches the name of the troff font is assumed to be a host
resident font program and is included in the PostScript width
table program.
There is no default.
.TP 1.0i
.OP \-L file
Use
.I file
as the PostScript prologue.
.br
The default is
.MW \*(dQ/trofftable.ps
.TP 1.0i
.OP \-S file
Use
.I file
as the shell library file.
Overrides the choice made with the
.OP \-T
option.
.TP 1.0i
.OP \-T name
Set the target device to
.IR name .
Device
.I name
means
.br
.MI \*(dF/dev name /shell.lib
is the shell library file.
There is no default.
.PP
One of
.OP \-T
or
.OP \-S
is required.
If both are given
.OP \-S
wins.
Either
.OP \-H
or
.OP \-C
can be used to include a host resident font.
.PP
The shell library file defines a collection of functions used to
build troff tables.
The default set of tables is the list of names returned by the
.MW AllTables
function.
Changes to the default list can be made by updating the
.MW BuiltinTables
function.
.PP
.I Shortname
is the name of the
.B troff
font and
.I longname
is the name of the PostScript font;
.I longname
can be omitted only if
.I shortname
is a default table name.
PostScript table programs created by
.B trofftable
return data to the host computer using PostScript's
.MW print
operator.
See
.BR hardcopy (1)
if you don't have access to the printer's serial port.
.SH EXAMPLES
Get the PostScript program that builds a width table for font
.MR R :
.EX
trofftable -Tpost R >R.ps
.EE
If a font is not in the default set include the
.B troff
and PostScript font names:
.EX
trofftable -TLatin1 GL Garamond-Light >GL.ps
.EE
A font must be available on the printer when the table is built.
Use
.OP \-H
or
.OP \-C
to include host resident fonts.
.SH WARNINGS
A width table will not build properly if the printer cannot access
the PostScript font.
.PP
The
.OP -TLatin1
option only works on PostScript printers that support the full
.SM ISO
Latin-1 character set.
The error message from older printers will likely indicate a missing
.MW ISOLatin1Encoding
array.
.SH FILES
.MW \*(dF/dev*/shell.lib
.br
.MW \*(dQ/dpost.ps
.br
.MW \*(dQ/trofftable.ps
.SH SEE ALSO
.BR dpost (1),
.BR hardcopy (1),
.BR postio (1),
.BR troff (1),
.BR buildtables (1),
.BR font (5)
