objtype=amd64
<$NXM/$objtype/mkfile

LIB=$NXM/$objtype/lib/libc.a
SFILES=\
	argv0.s\
	atom.s\
	cycles.s\
	getfcr.s\
	main9.s\
	main9p.s\
	memccpy.s\
	memchr.s\
	memcmp.s\
	memcpy.s\
	memmove.s\
	memset.s\
	muldiv.s\
	rdpmc.s\
	setjmp.s\
	sqrt.s\
	strcat.s\
	strchr.s\
	strcpy.s\
	strlen.s\
	tas.s\

CFILES=\
	_seek.c\
	getcallerpc.c\
	notejmp.c\

HFILES=$NXM/sys/include/libc.h

OFILES=${CFILES:%.c=%.$O} ${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$CFILES\
	$SFILES\

<$NXM/sys/src/cmd/mksyslib
