</$objtype/mkfile

LIB=/$objtype/lib/libdraw.a

FILES=\
	alloc\
	allocimagemix\
	arith\
	bezier\
	border\
	buildfont\
	bytesperline\
	chan\
	cloadimage\
	computil\
	creadimage\
	debug\
	defont\
	draw\
	drawrepl\
	egetrect\
	ellipse\
	emenuhit\
	event\
	font\
	freesubfont\
	getdefont\
	getrect\
	getsubfont\
	icossin\
	icossin2\
	init\
	keyboard\
	line\
	menuhit\
	mkfont\
	mouse\
	openfont\
	poly\
	loadimage\
	readcolmap\
	readimage\
	readsubfont\
	rectclip\
	replclipr\
	rgb\
	string\
	stringbg\
	stringsubfont\
	stringwidth\
	subfont\
	subfontcache\
	subfontname\
	unloadimage\
	window\
	writecolmap\
	writeimage\
	writesubfont\

HFILES=\
	/sys/include/draw.h\
	/sys/include/event.h\
	/sys/include/mouse.h\
	/sys/include/keyboard.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libdraw.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib
