</$objtype/mkfile

LIB=/$objtype/lib/libregexp.a
FILES=\
	regcomp\
	regerror\
	regexec\
	regsub\
	regaux\
	rregexec\
	rregsub\

HFILES=/sys/include/regexp.h\
	regcomp.h\

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libregexp.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib

test: test.$O $OFILES
	$LD -o test $prereq

test2: test2.$O $OFILES
	$LD -o test2 $prereq
