<$ROOT/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libframe.a
OFILES=\
	frbox.$O\
	frdraw.$O\
	frdelete.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frstr.$O\
	frutil.$O\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

<$ROOT/sys/src/cmd/mksyslib
