</$objtype/mkfile

LIB=/$objtype/lib/libbio.a
FILES=\
	bbuffered\
	bfildes\
	bflush\
	bgetrune\
	bgetc\
	bgetd\
	binit\
	boffset\
	bprint\
	bputrune\
	bputc\
	brdline\
	brdstr\
	bread\
	bseek\
	bwrite\
	bvprint\

HFILES=/sys/include/bio.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/386/lib/libbio.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib

