void		acommand(int);
void		attachproc(void);
long		ascval(void);
void		beieeedfpout(char*);
void		beieeesfpout(char*);
void		beieee80fpout(char*);
void		leieee80fpout(char*);
void		bkput(BKPT*, int);
void		bpwait(void);
int		charpos(void);
void		chkerr(void);
void		clrinp(void);
void		cmdmap(Map*);
void		cmdsrc(int, Map*, int, int);
void		cmdwrite(int, Map*, int);
int		command(char*, int);
int		convdig(int);
void		ctrace(int);
WORD		defval(WORD);
void		delbp(void);
void		done(void);
int		dprint(char*, ...);
Map*		dumbmap(int);
void		endline(void);
void		endpcs(void);
int		eol(int);
void		error(char*);
void		errors(char*, char*);
void		execbkpt(BKPT*, int);
char*		exform(int, int, char*, Map*, int, int, int);
int		expr(int);
ulong		findframe(ulong);
void		flush(void);
void		flushbuf(void);
long		fpin(char*);
int		get1(Map*, ulong, int, uchar *, int);
int		get2(Map*, ulong, int, ushort *);
int		get4(Map*, ulong, int, long *);
char*		getfname(void);
void		getformat(char*);
int		getnum(int (*)(void));
int		getreg(int);
void		grab(void);
void		iclose(int, int);
char*		ieeedtos(char*, ulong, ulong);
char*		ieeeftos(char*, ulong);
ulong		inkdot(long);
int		isfileref(void);
int		item(int);
void		killpcs(void);
void		kmproc(void);
void		kmprocset(int);
void		kmsys(void);
void		leieeedfpout(char*);
void		leieeesfpout(char*);
void		localaddr(char *, char *);
void		main(int, char**);
int		mapcore(void);
int		mapimage(void);
void		newline(void);
int		nextchar(void);
void		notes(void);
void		oclose(void);
void		outputinit(void);
void		printc(int);
void		printdate(long);
void		printesc(int);
void		printlocals(Symbol *, ADDR);
void		printmap(char*, Map*);
void		printparams(Symbol *, ADDR);
void		printparcel(ulong, int);
void		printpc(void);
void		printregs(int);
void		prints(char*);
void		printsource(long);
void		printsym(void);
void		printsyscall(void);
void		printtrace(int);
void		psymoff(long, int, char*);
int		put1(Map*, ulong, int, uchar*, int);
int		put2(Map*, ulong, int, ushort);
int		put4(Map*, ulong, int, long);
int		quotchar(void);
int		rdc(void);
int		readchar(void);
void		readsym(char*);
void		redirin(int, char*);
void		redirout(char*);
void		readfname(char *);
void		reread(void);
ulong		rget(int);
int		rname(char*);
void		rput(int, ulong);
void		rrest4(struct reglist*);
void		rsnarf4(struct reglist*);
int		runpcs(int, int);
void		runrun(int);
void		runstep(ulong, int);
BKPT*		scanbkpt(ADDR adr);
void		scanform(long, int, char*, Map*, int, int);
void		setbp(void);
void		setcor(void);
void		setsym(void);
void		setup(void);
void		setvec(void);
void		shell(void);
void		startpcs(void);
void		subpcs(int);
int		symchar(int);
int		term(int);
void		ungrab(void);
int		valpr(long, int);
int		varchk(int);
