# push pool.c over to the kernel

BEGIN {
	printf("/* THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT. */\n");
	printf("/*\n");
	printf(" * The master for this file is /sys/src/libdebugmalloc/pool.c\n");
	printf(" * This file was generated automatically by awk and mk.\n");
	printf(" */\n");
	printf("\n");

	printf("#include	\"u.h\"\n");
	printf("#include	\"../port/lib.h\"\n");
	printf("#include	\"mem.h\"\n");
	printf("#include	\"dat.h\"\n");
	printf("#include	\"fns.h\"\n");
	printf("#include	<pool.h>\n");
	printf("\n");
}

/^#include/ { next; }

{print;}
