<$ROOT/$objtype/mkfile

LIB=$ROOT/$objtype/lib/libhttpd.a
OFILES=\
	alloc.$O\
	checkcontent.$O\
	date.$O\
	fail.$O\
	gethead.$O\
	hio.$O\
	httpfmt.$O\
	httpunesc.$O\
	lower.$O\
	okheaders.$O\
	parse.$O\
	parsereq.$O\
	query.$O\
	redirected.$O\
	unallowed.$O\
	urlfmt.$O\
	urlunesc.$O\

HFILES=\
	$ROOT/sys/include/httpd.h\
	escape.h\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

<$ROOT/sys/src/cmd/mksyslib
