MKSHELL=rc
<$NXM/$objtype/mkfile


LIB=../lib.$O.a
OFILES=\
	keyfmt.$O\
	netcheck.$O\
	okpasswd.$O\
	readwrite.$O\
	readarg.$O\
	readln.$O\
	getauthkey.$O\
	log.$O\
	error.$O\
	fs.$O\
	rdbio.$O\
	querybio.$O\
	wrbio.$O\
	getexpiration.$O\


HFILES=$NXM/sys/include/auth.h $NXM/sys/include/authsrv.h ../authcmdlib.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

<$NXM/sys/src/cmd/mksyslib
CFLAGS=$CFLAGS -I..
