.ds dQ /usr/lib/postscript
.TH POSTDAISY 1 "DWB 3.2"
.SH NAME
.B postdaisy
\- PostScript translator for Diablo 630 files
.SH SYNOPSIS
\*(mBpostdaisy\f1
.OP "" options []
.OP "" files []
.SH DESCRIPTION
.B postdaisy
translates Diablo 630 daisy-wheel
.I files
into PostScript and writes the results on the
standard output.
If no
.I files
are specified, or if
.OP \-
is one of the input
.IR files ,
the standard input is read.
The following
.I options
are understood:
.TP 0.75i
.OP \-c num
Print
.I num
copies of each page.
By default only one copy is printed.
.TP
.OP \-f name
Print
.I files
using font
.IR name .
Any PostScript font can be used,
although the best results will only be
obtained with constant width fonts.
The default font is Courier.
.TP
.OP \-h num
Set the initial horizontal motion index to
.IR num .
Determines the character advance and the default
point size, unless the
.OP \-s
option is used.
The default is 12.
.TP
.OP \-m num
Magnify each logical page by the factor
.IR num .
Pages are scaled uniformly about the origin,
which is located near the upper left corner of
each page.
The default magnification is 1.0.
.TP
.OP \-n num
Print
.I num
logical pages on each piece of paper,
where
.I num
can be any positive integer.
By default
.I num
is set to 1.
.TP
.OP \-o list
Print pages whose numbers are given in the comma-separated
.IR list .
The list contains single numbers
.I N
and ranges
.IR N1\-\|N2 .
A missing
.I N1
means the lowest numbered page, a missing
.I N2
means the highest.
.TP
.OP \-p mode
Print
.I files
in either \*(mBportrait\fP or \*(mBlandscape\fP
.IR mode .
Only the first character of
.I mode
is significant.
The default
.I mode
is \*(mBportrait\fP.
.TP
.OP \-r num
Selects carriage return and line feed behavior.
If
.I num
is 1 a line feed generates a carriage return.
If
.I num
is 2 a carriage return generates a line feed.
Setting
.I num
to 3 enables both modes.
.TP
.OP \-s num
Use point size
.I num
instead of the default value set by the
initial horizontal motion index.
.TP
.OP \-v num
Set the initial vertical motion index to
.IR num .
The default is 8.
.TP
.OP \-x num
Translate the origin
.I num
inches along the positive x axis.
The default
coordinate system has the origin fixed near the
upper left corner of the page, with positive
x to the right and positive y down the page.
Positive
.I num
moves everything right.
The default offset is 0.25 inches.
.TP
.OP \-y num
Translate the origin
.I num
inches along the positive y axis.
Positive
.I num
moves text down the page.
The default offset is 0.25 inches.
.TP
.OP \-E name
Set the character encoding for text fonts to
.IR name .
Requesting
.I name
means include file
.MI \*(dQ/ name .enc \f1.
A nonexistent encoding file is silently ignored.
The default selects file
.MR \*(dQ/Default.enc .
.TP
.OP \-L file
Use
.I file
as the PostScript prologue.
.br
The default is
.MR \*(dQ/postdaisy.ps .
.PP
Three options allow insertion of arbitrary PostScript
at controlled points in the translation process:
.TP 0.75i
.OP \-C file
Copy
.I file
to the output file;
.I file
must contain legitimate PostScript.
.TP
.OP \-P string
Include
.I string
in output file;
.I string
must be legitimate PostScript.
.TP
.OP \-R action
Requests special
.I action
(e.g.,
.MR manualfeed )
on a per page or global basis.
The
.I action
string can be given as
.IR request ,
.IM request : page\f1\|,
or
.IM request : page : file\f1\|.
If
.I page
is omitted or given as 0, the request
applies to all pages.
If
.I file
is omitted, the request
lookup is done in
.MR \*(dQ/ps.requests .
.SH DIAGNOSTICS
A 0 exit status is returned if
.I files
were successfully processed.
.SH FILES
.MW \*(dQ/postdaisy.ps
.br
.MW \*(dQ/forms.ps
.br
.MW \*(dQ/ps.requests
.SH SEE ALSO
.BR dpost (1),
.BR postdmd (1),
.BR postio (1),
.BR postmd (1),
.BR postprint (1),
.BR postreverse (1),
.BR posttek (1),
.BR psencoding (1)
