.\" $Id: font2c.1,v 1.37 2005/10/20 19:46:55 ray Exp $
.TH FONT2C 1 "20 October 2005" 8.53 Ghostscript \" -*- nroff -*-
.SH NAME
font2c \- Write PostScript Type 0 or Type 1 font as C code
.SH SYNOPSIS
\fBfont2c\fR \fIfontnames\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
with the following options:

.ce
.B -q -dNODISPLAY -dWRITESYSTEMDICT

followed by the arguments from the command line.
This will write out a PostScript Type 0 or Type 1 font as C code
that can be linked with the interpreter.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 8.53.
.SH AUTHOR
artofcode LLC and Artifex Software, bug-gs at ghostscript.com, are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
