.\" $Id: pdfopt.1,v 1.36 2005/10/20 19:46:55 ray Exp $
.TH PDFOPT 1 "20 October 2005" 8.53 "Ghostscript Tools" \" -*- nroff -*-
.SH NAME
pdfopt \- Ghostscript PDF Optimizer
.SH SYNOPSIS
\fBpdfopt\fR [ \fIoptions\fR ] \fIinput.pdf output.pdf\fR
.SH DESCRIPTION
\fBpdfopt\fR uses \fBgs\fR(1) to convert the Adobe \fBPortable Document
Format\fR (PDF) file "input.pdf" to a so-called optimized form in
"output.pdf".  Optimization puts the elements of the file into a more linear
order and adds "hint" pointers, allowing Adobe's Acrobat(TM) products to
display individual pages of the file more quickly when accessing the file
through a network.
.PP
Note: input.pdf and output.pdf must not be the same.  If they are, the file
will probably be destroyed.  \fBpdfopt\fR currently does not check for this.
.SH FILES
Run "\fBgs -h\fR" to find the location of Ghostscript documentation on your
system, from which you can get more details.
.SH SEE ALSO
"Linearized PDF" in Adobe's PDF reference manual,
http://partners.adobe.com/asn/developer/acrosdk/DOCS/pdfspec.pdf
.SH VERSION
This document was last revised for Ghostscript version 8.53.
.SH AUTHOR
artofcode LLC and Artifex Software, bug-gs at ghostscript.com, are the
primary maintainers of Ghostscript.
