.\" $Id: pf2afm.1,v 1.37 2005/10/20 19:46:55 ray Exp $
.TH PF2AFM 1 "20 October 2005" 8.53 Ghostscript \" -*- nroff -*-
.SH NAME
pf2afm \- Make an AFM file from Postscript (PFB/PFA/PFM) font files using ghostscript
.SH SYNOPSIS
\fBpf2afm\fR  \fIfontfilename\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to make an AFM file from PFB / PFA and (optionally) PFM files.
Output goes to
.IR fontfilename.afm ,
which must not already exist.
.SH SEE ALSO
gs(1)
.br
pf2afm.ps in the Ghostscript lib directory.
.SH VERSION
This document was last revised for Ghostscript version 8.53.
.SH AUTHOR
artofcode LLC and Artifex Software, bug-gs at ghostscript.com, are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
