.\" $Id: pf2afm.1,v 1.1 2000/03/09 08:40:40 lpd Exp $
.TH PF2AFM 1 "3 February 2000" 6.0 Ghostscript \" -*- nroff -*-
.SH NAME
pf2afm \- Make an AFM file from Postscript (PFB/PFA/PFM) font files using ghostscript
.SH SYNOPSIS
\fBpf2afm\fR  \fIfontfilename\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to make an AFM file from PFB / PFA and (optionally) PFM files.
Output goes to
.IR fontfilename.afm ,
which must not already exist.
.SH SEE ALSO
gs(1)
.br
pf2afm.ps in the Ghostscript lib directory.
.SH VERSION
This document was last revised for Ghostscript version 6.0.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com> is the principal author of Ghostscript.
Russell J. Lang <rjl@aladdin.com> is the author of most of the MS Windows
code in Ghostscript.
This manpage by George Ferguson.

