.\" $Id: pfbtopfa.1,v 1.11.2.2 2002/02/01 05:31:25 raph Exp $
.TH PFBTOPFA 1 "31 January 2002" 7.04 Ghostscript \" -*- nroff -*-
.SH NAME
pfbtopfa \- Convert Postscript .pfb fonts to .pfa format using ghostscript
.SH SYNOPSIS
\fBpfbtopfa\fR \fIinput.pfb\fR \fI[output.pfa]\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a .pfb file into a .pfa file.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 7.04.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com> is the principal author of Ghostscript.
Russell J. Lang <rjl@aladdin.com> is the author of most of the MS Windows
code in Ghostscript.
This manpage by George Ferguson.

