.\" $Id: pfbtopfa.1,v 1.38 2005/10/20 19:46:55 ray Exp $
.TH PFBTOPFA 1 "20 October 2005" 8.53 Ghostscript \" -*- nroff -*-
.SH NAME
pfbtopfa \- Convert Postscript .pfb fonts to .pfa format using ghostscript
.SH SYNOPSIS
\fBpfbtopfa\fR \fIinput.pfb\fR \fI[output.pfa]\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a .pfb file into a .pfa file.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 8.53.
.SH AUTHOR
artofcode LLC and Artifex Software, bug-gs at ghostscript.com, are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
