.\" $Id: pfbtopfa.1,v 1.2.2.2 2000/11/28 01:31:26 raph Exp $
.TH PFBTOPFA 1 "27 November 2000" 6.32 Ghostscript \" -*- nroff -*-
.SH NAME
pfbtopfa \- Convert Postscript .pfb fonts to .pfa format using ghostscript
.SH SYNOPSIS
\fBpfbtopfa\fR \fIinput.pfb\fR \fI[output.pfa]\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a .pfb file into a .pfa file.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 6.32.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com> is the principal author of Ghostscript.
Russell J. Lang <rjl@aladdin.com> is the author of most of the MS Windows
code in Ghostscript.
This manpage by George Ferguson.

