.\" $Id: printafm.1,v 1.37 2005/10/20 19:46:55 ray Exp $
.TH PRINTAFM 1 "20 October 2005" 8.53 Ghostscript \" -*- nroff -*-
.SH NAME
printafm \- Print the metrics from a Postscript font in AFM format using ghostscript
.SH SYNOPSIS
\fBprintafm\fR \fIfontname\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to print the metrics from a font in AFM format.
Output goes to stdout.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 8.53.
.SH AUTHOR
artofcode LLC and Artifex Software, bug-gs at ghostscript.com, are the
primary maintainers of Ghostscript.
This manpage by George Ferguson.
