.\" $Id: ps2ps.1,v 1.44 2005/10/20 19:46:55 ray Exp $
.TH PS2PS 1 "20 October 2005" 8.53 "Ghostscript Tools" \" -*- nroff -*-
.SH NAME
ps2ps, eps2eps \- Ghostscript PostScript "distiller"
.SH SYNOPSIS
\fBps2ps\fR [ \fIoptions\fR ] \fIinput.ps output.ps\fR
.br
\fBeps2eps\fR [ \fIoptions\fR ] \fIinput.eps output.eps\fR
.SH DESCRIPTION
\fBps2ps\fR uses \fIgs\fR(1) to convert \fBPostScript\fR(tm) file
"input.ps" to simpler, normalized and (usually) faster PostScript in
"output.ps".  Normally the output is allowed to use PostScript Level 2
or Level 3 constructs, but the \fB\-dLanguageLevel=1\fR option restricts
the output to Level 1.
.PP
\fBeps2eps\fR performs the equivalent optimization for Encapsulated
PostScript (EPS) files.
.PP
Both accept any general Ghostscript command line options, and
respectively options specific to the pswrite and epswrite devices.
.SH FILES
Run "\fBgs -h\fR" to find the location of Ghostscript documentation on your
system, from which you can get more details.
.SH BUGS
The pswrite device used by both \fBps2ps\fR and \fBeps2eps\fR produces much
lower level output than is desirable. Use with caution.
.SH SEE ALSO
ps2pdf(1), ps2ascii(1), ps2epsi(1)
.SH VERSION
This document was last revised for Ghostscript version 8.53.
.SH AUTHOR
artofcode LLC and Artifex Software are the primary maintainers of Ghostscript.
Please send bug reports to <bug-gs@ghostscript.com>.
