.\" $Id: wftopfa.1,v 1.1 2000/03/09 08:40:40 lpd Exp $
.TH WFTOPFA 1 "3 February 2000" 6.0 Ghostscript \" -*- nroff -*-
.SH NAME
wftopfa \- Convert a Wadalab base font to Postscript .PFA (or .PFB)
format using ghostscript
.SH SYNOPSIS
\fBwftopfa\fR \fIfontname\fR
.SH DESCRIPTION
This script invokes
.BR gs (1)
to convert a Wadalab base font to Postscript .PFA (or .PFB)
format.
.SH SEE ALSO
gs(1)
.SH VERSION
This document was last revised for Ghostscript version 6.0.
.SH AUTHOR
L. Peter Deutsch <ghost@aladdin.com> is the principal author of Ghostscript.
Russell J. Lang <rjl@aladdin.com> is the author of most of the MS Windows
code in Ghostscript.
This manpage by George Ferguson.

