</$objtype/mkfile

TARG=\
	gpsfs\
	gpsevermore\
	
OFILES=\
	util.$O

BIN=/$objtype/bin/aux

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

</sys/src/cmd/mkmany

update:V:
	update $UPDATEFLAGS $UPDATE
