/*
 * print vesa coordinated video timings.
 */
#include <u.h>
#include <libc.h>
#include "vesacvt.h"

static int prsh;
static int prstruct;

static uvlong
divround(uvlong a, uvlong b)
{
	return (a + b/2) / b;
}

static void
modeprint(Cvt *cvt, ulong hfporch, ulong hbporch)
{
	print("/* generated by vesacvt; no borders & no interlace */\n");
	print("static Mode vesa%ldx%ldx%ld = {\n", cvt->wid, cvt->ht, cvt->hz);
	print("\t.name = \"%ldx%ld@%ldHz\",\n", cvt->wid, cvt->ht, cvt->hz);
	print("\t.x = %ld,\n", cvt->wid);
	print("\t.y = %ld,\n", cvt->ht);
	print("\n");

	print("\t/* h front porch %ld, h sync %ld, h back porch %ld */\n",
		hfporch, cvt->hsync, hbporch);
	print("\t.shb = %ld,\n", cvt->wid);
	print("\t.shs = %ld+%ld,\t\t/* sync start */\n", cvt->wid, hfporch);
	print("\t.ehs = %ld+%ld+%ld,\n", cvt->wid, hfporch, cvt->hsync);
	print("\t.ehb = %ld+%ld+%ld+%ld,\n",
		cvt->wid, hfporch, cvt->hsync, hbporch);
	print("\t.ht  = %ld+%ld+%ld+%ld,\n",
		cvt->wid, hfporch, cvt->hsync, hbporch);
	print("\n");

	print("\t/* v front porch %ld, v sync %ld, v back porch %ld */\n",
		cvt->vfporch, cvt->vsync, cvt->vbporch);
	print("\t.vbs = %ld,\n", cvt->ht);
	print("\t.vrs = %ld+%ld,\t\t/* retrace (sync) start */\n",
		cvt->ht, cvt->vfporch);
	print("\t.vre = %ld+%ld+%ld,\n", cvt->ht, cvt->vfporch, cvt->vsync);
	print("\t.vbe = %ld+%ld+%ld+%ld,\n",
		cvt->ht, cvt->vfporch, cvt->vsync, cvt->vbporch);
	print("\t.vt  = %ld+%ld+%ld+%ld,\n",
		cvt->ht, cvt->vfporch, cvt->vsync, cvt->vbporch);
	print("\n");

	print("\t.frequency = %ld,\n", cvt->pixfreq);
	print("\n");
	if (cvt->reducedblank) {
		print("\t.hsync = '+',\t\t/* reduced blanking cvt */\n");
		print("\t.vsync = '-',\n");
	} else {
		print("\t.hsync = '-',\t\t/* crt cvt */\n");
		print("\t.vsync = '+',\n");
	}
	print("\t.interlace = 0,\n");
	print("};\n");
}

static void
prvesacvt(ulong wid, ulong ht, ulong hz, int reducedblank)
{
	ulong hbackporch, hfrontporch, hfreq, fieldfreq;
	Cvt *cvt;

	cvt = vesacvt(wid, ht, hz, reducedblank);
	if (cvt == nil)
		sysfatal("no memory: %r");
	hbackporch  = cvt->hblank / 2;
	hfrontporch = cvt->hblank - hbackporch - cvt->hsync;
	hfreq = divround(cvt->pixfreq, cvt->totpix * 1000LL);	/* KHz */
	fieldfreq = divround(1000 * hfreq, cvt->totvlines);	/* Hz */

	if (prsh) {
		print("# cvt with%s reduced blanking\n",
			(cvt->reducedblank? "": "out"));
		print("hfrontporch=%lud hsync=%lud hbackporch=%lud\n"
			"vfrontporch=%lud vsync=%lud vbackporch=%lud\n"
			"pclk=%lud hfreq=%ludKHz hz=%lud\n",
			hfrontporch, cvt->hsync, hbackporch,
			cvt->vfporch, cvt->vsync, cvt->vbporch,
			cvt->pixfreq, hfreq, fieldfreq);
	} else if (prstruct)
		modeprint(cvt, hfrontporch, hbackporch);
	else {
		print("# cvt with%s reduced blanking\n",
			(cvt->reducedblank? "": "out"));
		print("h %lud %lud %lud\tv %lud %lud %lud\t"
			"pclk %lud hfreq %ludKHz hz %lud\n",
			hfrontporch, cvt->hsync, hbackporch,
			cvt->vfporch, cvt->vsync, cvt->vbporch,
			cvt->pixfreq, hfreq, fieldfreq);
	}
	free(cvt);
}

static void
usage(void)
{
	fprint(2, "usage: %s [-cms] width height hz\n", argv0);
	exits("usage");
}

void
main(int argc, char **argv)
{
	int rb = 1;

	ARGBEGIN{
	case 'c':		/* compute crt, not reduced blanking, timings */
		rb = 0;
		break;
	case 'm':		/* print aux/vga/vesadb.c Mode definition */
		prstruct = 1;
		break;
	case 's':		/* print shell variables */
		prsh = 1;
		break;
	default:
		usage();
		break;
	}ARGEND;
	if (argc != 3 || prsh && prstruct)
		usage();
	prvesacvt(atol(argv[0]), atol(argv[1]), atol(argv[2]), rb);
	exits(0);
}
