</$objtype/mkfile

TARG=plot
OFILES=plot.$O\

HFILES=plot.h\

LIB=libplot.a$O

BIN=/$objtype/bin
</sys/src/cmd/mkone

$LIB:
	cd libplot
	mk install

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.? y.debug y.output $TARG
	cd libplot
	mk clean

nuke:V:
	mk clean
	rm -f libplot.a[$OS]
