</$objtype/mkfile

TARG=jpg\
	gif\
	togif\
	ppm\
	toppm\
	png\
	topng\

IMFILES=\
	torgbv.$O\
	totruecolor.$O\
	writerawimage.$O\

HFILES=imagefile.h\

LIB=

BIN=/$objtype/bin
</sys/src/cmd/mkmany
c=`{sed -n 's/^O=//p' /$cputype/mkfile}

$O.jpg:		$IMFILES readjpg.$O jpg.$O
$O.gif:		$IMFILES readgif.$O gif.$O
$O.togif:	writegif.$O onechan.$O togif.$O torgbv.$O
$O.ppm:		$IMFILES readppm.$O ppm.$O
$O.toppm:	writeppm.$O multichan.$O toppm.$O
$O.png:		$IMFILES readpng.$O png.$O
$O.topng:	writepng.$O topng.$O

torgbv.$O:	ycbcr.h rgbv.h

ycbcr.h:	rgbycc.c
	$c^c rgbycc.c
	$c^l -o $c.rgbycc rgbycc.$c
	$c.rgbycc > ycbcr.h

rgbv.h:	rgbrgbv.c
	$c^c rgbrgbv.c
	$c^l -o $c.rgbrgbv rgbrgbv.$c
	$c.rgbrgbv > rgbv.h

nuke:V:	nuke-headers

nuke-headers:V:
	rm -f rgbv.h ycbcr.h
