void	accessdir(Iobuf*, Dentry*, int);
void	addfree(Device, long, Superb*);
long	balloc(Device, int, long);
void	bfree(Device, long, int);
int	byname(void*, void*);
int	byuid(void*, void*);
int	Cconv(Op*);
int	checkname(char*);
int	checktag(Iobuf*, int, long);
void 	cmd_user(void);
char*	cname(char*);
int	con_attach(int, char*, char*);
int	con_clone(int, int);
int	con_create(int, char*, int, int, long, int);
int	con_open(int, int);
int	con_path(int, char*);
int	con_read(int, char*, long, int);
int	con_remove(int);
int	con_stat(int, char*);
int	con_clri(int);
int	con_session(void);
int	con_walk(int, char*);
int	con_write(int, char*, long, int);
int	con_wstat(int, char*);
int	convD2M(Dentry*, char*);
int	convnD2M(Dentry*, char*);
int	convM2D(char*, Dentry*);
int	convnM2D(char*, Dentry*);
int	convM2S(char*, Fcall*, int);
int	convS2M(Fcall*, char*);
void	cprint(char*, ...);
int	crack(File*, Fcall*);
void	datestr(char*, long);
void	dbufread(Iobuf*, Dentry*, long);
int	Dconv(Op*);
int	devcmp(Device, Device);
Iobuf*	dnodebuf(Iobuf*, Dentry*, long, int);
void	dofilter(Filter*);
int	doremove(File *, int);
void	dtrunc(Iobuf*, Dentry*);
void	exit(void);
int	Fconv(Op*);
ulong	fakeqid(Dentry*);
Float	famd(Float, int, int, int);
int	fchar(void);
ulong	fdf(Float, int);
void	fileinit(Chan*);
File*	filep(Chan*, int, int);
int	fname(char*);
void	formatinit(void);
void	freefp(File*);
void	freewp(Wpath*);
Filsys*	fsstr(char*);
void	f_attach(Chan*, Fcall*, Fcall*);
void	f_auth(Chan*, Fcall*, Fcall*);
void	f_clone(Chan*, Fcall*, Fcall*);
void	f_clunk(Chan*, Fcall*, Fcall*);
void	f_create(Chan*, Fcall*, Fcall*);
void	f_errstr(Chan*, Fcall*, Fcall*);
void	f_nop(Chan*, Fcall*, Fcall*);
void	f_flush(Chan*, Fcall*, Fcall*);
void	f_open(Chan*, Fcall*, Fcall*);
void	f_read(Chan*, Fcall*, Fcall*);
void	f_remove(Chan*, Fcall*, Fcall*);
void	f_session(Chan*, Fcall*, Fcall*);
void	f_stat(Chan*, Fcall*, Fcall*);
void	f_userstr(Chan*, Fcall*, Fcall*);
void	f_walk(Chan*, Fcall*, Fcall*);
void	f_clwalk(Chan*, Fcall*, Fcall*);
void	f_write(Chan*, Fcall*, Fcall*);
void	f_wstat(Chan*, Fcall*, Fcall*);
int	Gconv(Op*);
Iobuf*	getbuf(Device, long, int);
Dentry*	getdir(Iobuf*, int);
long	getraddr(Device);
void	hexdump(void*, int);
int	iaccess(File*, Dentry*, int);
long	indfetch(Iobuf*, Dentry*, long, long , int, int);
int	ingroup(int, int);
void	iobufinit(void);
int	leadgroup(int, int);
File*	newfp(Chan*);
Qid	newqid(Device);
void	newstart(void);
Wpath*	newwp(void);
void	p9fcall(Chan*, Fcall*, Fcall*);
void	panic(char*, ...);
int	prime(long);
void	putbuf(Iobuf*);
void	rootream(Device, long);
void	settag(Iobuf*, int, long);
void	strrand(void*, int);
int	strtouid(char*);
int	strtouid1(char*);
int	superok(Device, long, int);
void	superream(Device, long);
void	sync(char*);
int	syncblock(void);
int	Tconv(Op*);
long	time(void);
Tlock*	tlocked(Iobuf*, Dentry*);
long	toytime(void);
void	uidtostr(char*,int);
void	uidtostr1(char*,int);
