</$objtype/mkfile

HFILES=\
	deflate.h\
	gzip.h\
	zip.h\

TARG=\
	gzip\
	gunzip\
	zip\
	unzip\

LIB=libdeflate.a.$O
LIBOFILES=\
	crc.$O\
	deflate.$O\
	inflate.$O\

BIN=/$objtype/bin/

</sys/src/cmd/mkmany

$LIB(%.$O):N: %.$O
$LIB:	${LIBOFILES:%=$LIB(%)}
	names = `{echo $newprereq |sed 's/ /\n/g' |sed -n 's/'$LIB'\(([^)]+)\)/\1/gp'}
	ar vu $LIB $names
	rm $names
